### ISSUE TITLE
err:ninecfg:nine_set d3d9-nine.dll not found

### ISSUE THREAD

**Issue by WuShichao** [iXit/wine-nine-standalone#1]
Hello, I use Padoka Stable PPA, when I compiling wine-nine-standalone, I get this error:
`installing 32bit binaries to /home/wushichao/.wine/dosdevices/c:/windows/syswow64`
`installing 64bit binaries to /home/wushichao/.wine/dosdevices/c:/windows/system32`
`enabling gallium nine`
`0034:err:ninecfg:nine_set d3d9-nine.dll not found.`
 `done`

**Comment by dhewg** [comment]
That's output from `nine-install.sh`.
Did you use `release.sh` to build it? Did that succeed?

**Comment by WuShichao** [comment]
@dhewg when I `locate dadadapter9`, I do have it:
![default](https://user-images.githubusercontent.com/6574526/52192074-d5d6e280-2882-11e9-977a-ac6fa24f8e1e.png)

**Comment by dhewg** [comment]
That's the runtime package, you need its headers and `pkgconfig/d3d.pc`.
Which are in `mesa-common-dev` for this PPA, see https://github.com/iXit/wine-nine-standalone/wiki/Debian-and-Ubuntu

**Comment by WuShichao** [comment]
@dhewg Thanks, but I can't install `mesa-common-dev`, because it relies on `libd3dadapter9-mesa (= 18.2.2-0ubuntu1~18.04.1)`, its version is still 18.2.2, but the mesa version in Padoka Stable PPA is already `18.3.3-1~c~padoka0`, which makes it can't be installed.

**Comment by dhewg** [comment]
Sounds like you mixed mesa packages from the ubuntu repos and that ppa which conflict with each other. You need to install all mesa related packages from only one source.

It may be easier to just grab the release binaries, which I specifically provide to avoid all those problems with outdated packages ;)

**Comment by WuShichao** [comment]
@dhewg You're right, I just misunderstood your meaning of ` with Debian buster and **Ubuntu cosmic** the required development packages are:`, now I know that's for users not using Padoka Stable PPA :)
Now I can install `mesa-common-dev`, but I still get this error:
![default](https://user-images.githubusercontent.com/6574526/52194808-4cc6a800-2890-11e9-90cd-879ef66a6142.png)

**Comment by dhewg** [comment]
`pkgconfig/d3d.pc` is still missing I guess? Try `dpkg -S d3d.pc`
It is in `mesa-common-dev` for oibaf's ppa, I thought it's the same for padoka?
Anyway, that file from a -dev package is required

As a side note, just c&p shell output here, there's no need to post screenshots

**Comment by WuShichao** [comment]
@dhewg Thanks, here is the result:
`wushichao@family:~/wine-nine-standalone$ dpkg -S d3d.pc`
`mesa-common-dev:amd64: /usr/lib/x86_64-linux-gnu/pkgconfig/d3d.pc`
But when I compiling it, it can find d3d, but I get new error:
`/usr/include/d3dadapter/present.h:26:10: fatal error: d3d9.h: no such file or directory`

**Comment by dhewg** [comment]
Well, it tells you what's missing...
Just grab a binary release. Even if you fixed that error, I suspect you run into the next issue with a buggy `winegcc` afterwards.

**Comment by WuShichao** [comment]
@dhewg I'm using Linux Mint 19.1 using Padoka PPA from very beginning, you mean I need grab wine-nine-standalone's binary release?

**Comment by dhewg** [comment]
Yeah, `gallium-nine-standalone-v0.2.tar.gz` from https://github.com/iXit/wine-nine-standalone/releases/tag/v0.2 should just work, including on Mint

**Comment by WuShichao** [comment]
@dhewg I grab the binary release, and just run `./nine-install.sh`, still get the same error:
`installing 32bit binaries to /home/wushichao/.wine/dosdevices/c:/windows/syswow64`
`installing 64bit binaries to /home/wushichao/.wine/dosdevices/c:/windows/system32`
`enabling gallium nine`
`0034:err:ninecfg:nine_set d3d9-nine.dll not found.`
`done`
But I can find `d3d9-nine.dll.so` in binary release's fold.

**Comment by dhewg** [comment]
Ok, well that's weird.
Please paste the output of `find /home/wushichao/.wine/drive_c/ -name \*nine\* | xargs ls -la`

**Comment by dhewg** [comment]
> `0009:err:d3d9nine:d3dadapter9_new No available native adapters in system.`
That means no gallium drivers, do you use AMD's binary drivers on that box?

**Comment by WuShichao** [comment]
@dhewg I also use Padoka Stable PPA on my laptop.

**Comment by dhewg** [comment]
Hm, the error makes it sounds like you're not.
What does `glxinfo | grep OpenGL` say?

**Comment by WuShichao** [comment]
@dhewg It's Padoka PPA, I'm very sure :)
nightwing@halo:~$ glxinfo | grep OpenGL
ATTENTION: default value of option vblank_mode overridden by environment.
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.3.3 - padoka PPA
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 18.3.3 - padoka PPA
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 18.3.3 - padoka PPA
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:

**Comment by dhewg** [comment]
Ok it is, but that's an Intel GPU, not a AMD one :P

**Comment by WuShichao** [comment]
@dhewg 
When I run neofetch, you can see my two GPUs:
GPU: Intel Haswell Mobile
GPU: AMD Radeon HD 8670A/8670M/8690M

**Comment by WuShichao** [comment]
@dhewg 
nightwing@halo:~$ DRI_PRIME=1 glxinfo | grep OpenGL
ATTENTION: default value of option vblank_mode overridden by environment.
OpenGL vendor string: X.Org
OpenGL renderer string: AMD HAINAN (DRM 2.50.0, 4.15.0-45-generic, LLVM 7.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.3.3 - padoka PPA
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5 (Compatibility Profile) Mesa 18.3.3 - padoka PPA
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.3.3 - padoka PPA
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

**Comment by dhewg** [comment]
So try `DRI_PRIME=1` with wine/nine?

**Comment by WuShichao** [comment]
@dhewg Thank you very much!

**Comment by dhewg** [comment]
yay
