### ISSUE TITLE
Mafia 1.3 - INVALIDCALL

### ISSUE THREAD

**Issue by dungeon007** [iXit/wine-nine-standalone#100]
Via d3d8to9, winde3d or dxvk works, so nine only...

 Retal version starts with nine, while patched to 1.3 raises invalid call. That in a game happens in menu, but with a trace it seems happens immediately 🤣

https://www.dropbox.com/s/p76jzq7q255kxke/mafia13.trace.xz?dl=0

**Comment by axeldavy** [comment]
That trace uses a format not supported by the graphic card, and it's ok not to display support for it according to the caps reported on windows. Wine supports the format though so game tries to use it, thus the crash in the trace.
The crash in the menu must be a different issue

**Comment by dungeon007** [comment]
Anyway it owrks on wined3d and dxvk.
But sure, i suspected how could be that there are two issues in one here.

**Comment by dungeon007** [comment]
@axeldavy
How goes about this one taken from Windows:
https://www.dropbox.com/s/cu69h89871sz7jb/mafia13-win.trace.xz?dl=0
seems shows a beautuful crash with nine. 🤣

**Comment by axeldavy** [comment]
No crash here, so I must have fixed it in my local branch. Fix sent soon then.

**Comment by axeldavy** [comment]
I updated Ixit/Mesa-3D master. Should work fine on it.

**Comment by dungeon007** [comment]
Hm, game here still hangs in menu, could be something with mesa compile flags again...

**Comment by dungeon007** [comment]
Nope, not flags. csmt on/off, nope... game just hangs with nine only and throwing this:
https://i.postimg.cc/fyJC3b4X/2021-03-12-21-00-32-608x580.png

**Comment by axeldavy** [comment]
It seems random. If I relaunch several times I can make it crash. Probably some corruption issues

**Comment by axeldavy** [comment]
Alright, it was passing invalid locking flags, which returned an error.
Fixed on master (ignore the flags).

**Comment by dungeon007** [comment]
Ignore flags working.

**Comment by dungeon007** [comment]
Now only if that car minimap isnt somewhat broken (these car lines goes out of circle) in game and shadows to not flicker... these are another bugs i didnt spotted with dxvk, but at least it is does hang anymore.

**Comment by dungeon007** [comment]
And perf isnt right in it really... seems needs perf optimisations fixeges like Halo. 🤣
Seems to be just like Sniper Elite - Berlin 1945, also minimap broken there and perf difference huge. Kind of double faster than wined3d, but also double slower than dxvk>vulkan.

**Comment by axeldavy** [comment]
Well I guess I need a trace with the broken minimap.
And a log with NINE_DEBUG=vbuf,device and the game killed at the scene with the perf issue (or alternatively trace)

**Comment by dungeon007** [comment]
Just found that shadows does not flicker with override_vendorid=4318 , seems to be some of these that like vendor overrides 🤣

**Comment by dungeon007** [comment]
Will do a trace of Sniper Elite later on, about that minimap broken... that couldnt be so seen so easely in Mafia.

**Comment by axeldavy** [comment]
Maybe it hits different rendering paths with the vendor override. If so it is interesting to compare what changes and fix the buggy path.

**Comment by dungeon007** [comment]
Drived around and indeed shadow does not flicker with override_vendorid=4318, so likely does something else on that path.

**Comment by dungeon007** [comment]
Well, these shadows would need much more testing, as it start to flicker even with override just on a different part of the city... much less with override, but still 🤣

**Comment by dungeon007** [comment]
Intel override behave like nvidia one on these shadows, looks like there is no flicker but if i go to certain parts of the city (just doing Free Ride>second street, so just right>right) it starts there too... just on amd it starts near immediately and constantly.
 And to note likely isnt something due to wrapper, as on dxvk ultimately no flickering shadows anywhere, so i guess it is possible to fix them. 🤣

**Comment by dungeon007** [comment]
Well, lets try to fix that borked minimap first, maybe these bugs are connected somehow with shadows...
Here is trace of Sniper Elite minimap which is big with nine, works in winde3d or dxvk:
https://drive.google.com/file/d/1g4Tc1UTgpUS4Hn1sslkVb9ubhBYV3YlD/view?usp=sharing
I guess that is the same bug like in Mafia, where some cars getting out of minimap circle. 🤣

**Comment by dungeon007** [comment]
I would close this as first issue was fixed, troubled with minimap could continue here: 
https://github.com/iXit/wine-nine-standalone/issues/108
