### ISSUE TITLE
True crime

### ISSUE THREAD

**Issue by dungeon007** [iXit/wine-nine-standalone#102]
d3d8to9, game does not run with nine... Neither it runs with wined3d:
https://appdb.winehq.org/objectManager.php?sClass=version&iId=13300
Nor it runs with dxvk>radv.
 So what is the bug, if it does not work anywhere?
 It actually starts to run everywhere else, if at least once is run via dxvk>amdvlk.
 Game config file seems does not change, replaying trace does not show it, now that is some kind of mystery... i mean true crime 🤣
 I guess, it must be something like in Mafia 1.3, ignore the flags, as it throws similar thing... invalid mov1, sometimes call, randomly...

**Comment by dungeon007** [comment]
I mean that is so funny, you have to run it on amdvlk to be able to run it elsewhere afterwards, otherwise it does not work.
 Sorry about this bug, but well it does not work with nine by default 🤣

**Comment by dungeon007** [comment]
Or might be some vendor thingie that fixes it like that with amdvlk, no idea.
Hm, I probably have to do clean wine room, maybe it throwed away somewhere something 🤣

**Comment by axeldavy** [comment]
Well I guess you will need indeed to create several wine prefix with the game just installed, and run with the thing that works and check for any change in the wineprefix

**Comment by dungeon007** [comment]
Blah, this is about resolution in that ini file game creates in its folder, default 640x480... i just have to specify something else there. Well somehow amdvlk fixes this, but all alse dont.
 So, It is not a big issue, one just to have to write something there or in case of runing widescreen script: https://github.com/ThirteenAG/WidescreenFixesPack/releases/tag/truecrimesola
one will sepecify something else anway, so...
