### ISSUE TITLE
Shrek 2 (in 1)

### ISSUE THREAD

**Issue by dungeon007** [iXit/wine-nine-standalone#105]
Might be some similar cause like in https://github.com/iXit/wine-nine-standalone/issues/97 , but anyway since no one commented, no idea maybe it was not so clear there 🤣. Anyway, here i go again since this is more or less common with nine, it might help...

 Shrek 2, this is Unreal Engine 2 D3D8 game, so d3d8to9 involved...

 DXVK (either by radv or via amdvlk) render both water reflection and shadow correctly.
 WINED3D render reflection correcty, but shadows incorrectly... shadow looks too dark.
 NINE render both reflections and shadows incorrectly. Shadows too dark like WINED3D and reflection is something like a opposite of what it should reflect.

 Trace here: https://drive.google.com/file/d/123rQrMUIjLvIDCe1sgw1eK5keuwpG-he/view?usp=sharing

**Comment by axeldavy** [comment]
Thanks for the trace. I managed to fix the two issues (two unrelated ff issues) with the trace. Will be pushed shortly.
