### ISSUE TITLE
Revo benchmark perf regression

### ISSUE THREAD

**Issue by dungeon007** [iXit/wine-nine-standalone#107]
Revo benchmark seems slower now

 http://www.pouet.net/prod.php?which=54588

 Hm, that was faster than wined3d about 23% and 33% above dxvk and now it seems isnt anymore.

 BTW i run these demos as benchmarks for D3D9 on NINE too, also fr-025 🤣

 http://www.pouet.net/prod.php?which=9450

 That one seems to hate thread_submit a bit, depending how res is set up  🤣 anyway...

 They arent popular i guess without commandline phoronix benchmark requirement 🤣... but i found them usuful too, nine was faster there but now on fr-043 seems it isnt anymore.
 have to do some bisect there it seems.

**Comment by dungeon007** [comment]
It is called rove i know, it have text typo joke so i always say revo in return, sorry about that 🤣

**Comment by axeldavy** [comment]
As your punishment, you'll have to do the bisect

**Comment by dungeon007** [comment]
Sure i already doing it, just not sure if anyone run this as a bench, maybe it is just me seeing this 🤣

**Comment by dungeon007** [comment]
Does not seem NINE bug
Just Marek break something with:
https://gitlab.freedesktop.org/mesa/mesa/-/commit/b42c6ff6f61b2bd731cd6cefc5c8bd6c623dc58a
but OK not for this bug... for this bug it was just disabling SDMA:
https://gitlab.freedesktop.org/mesa/mesa/-/commit/205f1d79e2464bf565dd02a9cb86ad7e5a3bf29d
Later on he removed SDMA:
https://gitlab.freedesktop.org/mesa/mesa/-/commit/1f31a216640f294ce310898773d9b42bda5d1d47
 Never spot these corruptions with sdma on this gfx7 APU... seems i just didnt noticed on time, that we are supposted to be slower here and there. 🤣

**Comment by dungeon007** [comment]
@axeldavy Hm, yet another bisection... your tree does not seems to run many apps with this 🤣
 
https://github.com/iXit/Mesa-3D/commit/cb365ac4e3925d179a0610ef7f60456d0ce67cde#diff-41cf08eeb3206aaad1f27b3848f534e0b71dfea05d8a837aa5ba8bea99bafce2

**Comment by axeldavy** [comment]
indeed, had it disabled locally.

But now looking at the commit it's obvious why lol. The condition is 
reversed.

**Comment by dungeon007** [comment]
It is so obvious that these conditions maks various PITA bugs. 
 Not sure what they were they doing there with util_float_to_half and util_half_to_float, adding, removing, adding... and finnaly borked, Marek doing one optimization with breaking another... i think that is crazy, but that is just mine opinion 🤣
 Same opinion on these true, false, none, disabled... meson flags... that just isnt bisection friendly 🤣

**Comment by dungeon007** [comment]
So lost 20% of perf here with removed SDMA on Rove bench, hopefully next wont be removeal of HYPERZ. 🤣

**Comment by dungeon007** [comment]
Well, not nine regression, so closing this
