### ISSUE TITLE
Gallium nine black screen on intel crocus

### ISSUE THREAD

**Issue by CTRL-ALT-DEL-92** [iXit/wine-nine-standalone#114]
Hi again,

I've installed mesa through oibaf ppa, the crocus driver works just fine, wine correctly detects gallium nine, but every application that use gallium nine shows just a black screen the audio works but nothing is shown on the screen. I'm trying to run the psxfin emulator (it works like it should with wined3d) when gallium nine is active just a black screen is shown. When I run psxfin through terminal (with nine active), these output are shown: io@io-ThinkPad-T410:~/Scrivania/psxfin v.1.13$ wine psxfin.exe
002c:fixme:winediag:LdrInitializeThunk wine-staging 6.10 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
0064:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0064:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
005c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
005c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
007c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
007c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
008c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
008c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
00cc:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
00cc:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0110:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0110:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0118:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0118:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
Native Direct3D 9 v0.8.0.385-release is active.
For more information visit https://github.com/iXit/wine-nine-standalone
fixme:d3d9nine:DRIPresentGroup_GetMultiheadCount (0x980840), stub!
fixme:d3d9nine:DRIPresentGroup_GetMultiheadCount (0x980840), stub!

**Comment by sjnewbury** [comment]
@CTRL-ALT-DEL-92, is MESA_LOADER_DRIVER_OVERRIDE=crocus set?

**Comment by CTRL-ALT-DEL-92** [comment]
Hi 

Crocus is set system wide through the dri irc file <driconf>
  <device driver="loader" kernel_driver="i915">
    <option name="dri_driver" value="crocus" />
  </device>
</driconf>
It works just fine  is more responsive than the i965 one. Thanks for your support

**Comment by sjnewbury** [comment]
Which version of wine are you using? Any patches applied?

The "child window rendering" patchset from Rémi Bernon which is included in Proton contains the following patch:

`commit 512d3671b38e273821149c83e6154e5490a22567
Author: Rémi Bernon <rbernon@codeweavers.com>
Date:   Thu Mar 11 23:27:57 2021 +0100

    winex11.drv: Remove unused X11DRV_GET_DRAWABLE ExtEscape code.

    Wine-Bug: https://bugs.winehq.org/show_bug.cgi?id=45277

diff --git a/dlls/winex11.drv/init.c b/dlls/winex11.drv/init.c
index 88ef1e3e2f8..cdb3dd931e9 100644
--- a/dlls/winex11.drv/init.c
+++ b/dlls/winex11.drv/init.c
@@ -224,14 +224,6 @@ static INT CDECL X11DRV_ExtEscape( PHYSDEV dev, INT escape, INT in_count, LPCVOI
                     return TRUE;
                 }
                 break;
-            case X11DRV_GET_DRAWABLE:
-                if (out_count >= sizeof(struct x11drv_escape_get_drawable))
-                {
-                    struct x11drv_escape_get_drawable *data = out_data;
-                    data->drawable = physDev->drawable;
-                    return TRUE;
-                }
-                break;
             case X11DRV_PRESENT_DRAWABLE:
                 if (in_count >= sizeof(struct x11drv_escape_present_drawable))
                 {
diff --git a/dlls/winex11.drv/x11drv.h b/dlls/winex11.drv/x11drv.h
index 4dbd698ef53..394cdb3c38e 100644
--- a/dlls/winex11.drv/x11drv.h
+++ b/dlls/winex11.drv/x11drv.h
@@ -287,7 +287,6 @@ extern int *get_window_surface_mapping( int bpp, int *mapping ) DECLSPEC_HIDDEN;
 enum x11drv_escape_codes
 {
     X11DRV_SET_DRAWABLE,     /* set current drawable for a DC */
-    X11DRV_GET_DRAWABLE,     /* get current drawable for a DC */
     X11DRV_START_EXPOSURES,  /* start graphics exposures */
     X11DRV_END_EXPOSURES,    /* end graphics exposures */
     X11DRV_PRESENT_DRAWABLE, /* present the drawable on screen */
@@ -301,14 +300,6 @@ struct x11drv_escape_set_drawable
     RECT                     dc_rect;      /* DC rectangle relative to drawable */
 };

-struct x11drv_escape_get_drawable
-{
-    enum x11drv_escape_codes code;         /* escape code (X11DRV_GET_DRAWABLE) */
-    Drawable                 drawable;     /* X drawable */
-    Drawable                 gl_drawable;  /* GL drawable */
-    int                      pixel_format; /* internal GL pixel format */
-};
-
 struct x11drv_escape_present_drawable
 {
     enum x11drv_escape_codes code;         /* escape code (X11DRV_PRESENT_DRAWABLE) */`

This breaks gallium-nine-standalone.

**Comment by CTRL-ALT-DEL-92** [comment]
Hi,

Nine works just fine I've played gta vice city with nine enabled with solid framerate. Psxfin does not work though, but it doesn't with dxvk as well, so it must be something with the emulatore. Snes 9x works too and just fine. Thanks for your fast support and kindness. I'll close this issue right now. Bye
