### ISSUE TITLE
TES IV oblivion blackscreen issue intro video black screen

### ISSUE THREAD

**Issue by CTRL-ALT-DEL-92** [iXit/wine-nine-standalone#115]
Dear Gallium nine developers,

I'm facing a problem with oblivion, the game is rendered just fine with gallium nine (considering my old hardware) but the intro video and the menu background is all black. 
![oblivion blackscreen](https://user-images.githubusercontent.com/78966095/124365241-fae40100-dc46-11eb-8343-87083d1c3e63.png)

The game itself works just fine. I'm using gallium nine on crossover for linux, on a thinkpad t410 with an Ironlake igpu using the newest mesa (through oibaf ppa) and the gallium driver crocus. Since I'm using crossover I was able to create a cxlog, a debug text file maybe it can help you. Here is its output: Running command: "C:\\users\\crossover\\Start Menu\\Oblivion.lnk"
Bottle: nine
Debug channels: 
Extra environment variables: 

CrossOver 21.0.0~beta1
Install location: /opt/cxoffice
64-bit OS
Desktop session: xfce
Window manager: Xfwm4
Locale: it_IT.UTF-8

Contents of /etc/os-release:
NAME="Linux Mint"
VERSION="20.1 (Ulyssa)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.1"
VERSION_ID="20.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=ulyssa
UBUNTU_CODENAME=focal

cxdiag output:
[Properties]
"vulkan.present"="yes"

[MissingGStreamer1Bad2]
"Title"="The gst-plugins-bad 32-bit GStreamer plugins appear to be missing h264parse"

[MissingGStreamer1Libav]
"Title"="The gst-libav 32-bit GStreamer plugins appear to be missing avdec_eac3"

[Properties]
"display.depth"="24"

[Properties]
"display.dpi"="-1.0"

[Properties]
"opengl.vendor"="Intel"

[Properties]
"opengl.version"="2.1 Mesa 21.2.0-devel (git-4698755 2021-07-03 focal-oibaf-ppa)"

[Properties]
"opengl.renderer"="Mesa Intel(R) HD Graphics (ILK)"

[Properties]
"opengl.glsl_version"="1.20"

[Properties]
"opengl.extensions"="GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_3DFX_texture_compression_FXT1 GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_ATI_fragment_shader GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_NV_fog_distance GL_NV_half_float GL_APPLE_packed_pixels GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_texture_array GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_seamless_cubemap_per_texture GL_ARB_ES2_compatibility GL_ARB_debug_output GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_texture_lod GL_ARB_texture_query_lod GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_copy_image GL_NV_texture_barrier GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_EXT_direct_state_access GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_base_instance GL_ARB_compressed_texture_pixel_storage GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_texture_storage GL_AMD_shader_trinary_minmax GL_ARB_clear_buffer_object GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_invalidate_subdata GL_ARB_program_interface_query GL_ARB_vertex_attrib_binding GL_KHR_debug GL_KHR_texture_compression_astc_ldr GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_seamless_cubemap_per_texture GL_ARB_shader_group_vote GL_ARB_shading_language_include GL_ARB_texture_mirror_clamp_to_edge GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_integer_mix GL_ARB_clip_control GL_ARB_get_texture_sub_image GL_ARB_texture_barrier GL_EXT_polygon_offset_clamp GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_ARB_parallel_shader_compile GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_ARB_polygon_offset_clamp GL_ARB_texture_filter_anisotropic GL_EXT_semaphore GL_EXT_semaphore_fd GL_KHR_parallel_shader_compile GL_EXT_EGL_image_storage GL_EXT_shader_framebuffer_fetch_non_coherent GL_EXT_EGL_sync GL_EXT_demote_to_helper_invocation "

[OpenglNoGLSL130]
"Title"="OpenGL shading language version is older than 1.30"

[OpenglNoD3D10]
"Title"="The OpenGL capabilities are insufficient for Direct3D 10 support"

cxdiag64 output:
[Properties]
"vulkan.present.amd64"="yes"

[Properties]
"display.depth"="24"

[Properties]
"display.dpi"="-1.0"

[Properties]
"opengl.vendor"="Intel"

[Properties]
"opengl.version"="2.1 Mesa 21.2.0-devel"

[Properties]
"opengl.renderer"="Mesa Intel(R) HD Graphics (ILK)"

[Properties]
"opengl.glsl_version"="1.20"

[Properties]
"opengl.extensions"="GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_3DFX_texture_compression_FXT1 GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_ATI_fragment_shader GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_NV_fog_distance GL_NV_half_float GL_APPLE_packed_pixels GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_texture_array GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_seamless_cubemap_per_texture GL_ARB_ES2_compatibility GL_ARB_debug_output GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_texture_lod GL_ARB_texture_query_lod GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_copy_image GL_NV_texture_barrier GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_EXT_direct_state_access GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_base_instance GL_ARB_compressed_texture_pixel_storage GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_texture_storage GL_AMD_shader_trinary_minmax GL_ARB_clear_buffer_object GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_invalidate_subdata GL_ARB_program_interface_query GL_ARB_vertex_attrib_binding GL_KHR_debug GL_KHR_texture_compression_astc_ldr GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_seamless_cubemap_per_texture GL_ARB_shader_group_vote GL_ARB_shading_language_include GL_ARB_texture_mirror_clamp_to_edge GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_integer_mix GL_ARB_clip_control GL_ARB_get_texture_sub_image GL_ARB_texture_barrier GL_EXT_polygon_offset_clamp GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_ARB_parallel_shader_compile GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_ARB_polygon_offset_clamp GL_ARB_texture_filter_anisotropic GL_EXT_semaphore GL_EXT_semaphore_fd GL_KHR_parallel_shader_compile GL_EXT_EGL_image_storage GL_EXT_shader_framebuffer_fetch_non_coherent GL_EXT_EGL_sync GL_EXT_demote_to_helper_invocation "

[OpenglNoGLSL130.amd64]
"Title"="OpenGL shading language version is older than 1.30"

[OpenglNoD3D10.amd64]
"Title"="The OpenGL capabilities are insufficient for Direct3D 10 support"

***** Sat Jul  3 21:29:35 2021
Starting: '/opt/cxoffice/bin/cxstart' '--bottle' 'nine' '--new-console' '--workdir' 'C:\users\crossover\Start Menu' '--' 'C:\users\crossover\Start Menu\Oblivion.lnk'

CXConfig->read(/opt/cxoffice/etc/cxoffice.conf)
CXConfig->read(/home/io/.cxoffice/cxoffice.conf)
Product version=21.0.0.33696
2173: Grabbing the '/tmp/.wine-1000/bottle-805-142b4b.lock' lock
2173: Got the '/tmp/.wine-1000/bottle-805-142b4b.lock' lock
CXConfig->read(/home/io/.cxoffice/nine/cxbottle.conf)
Mode = 'private'
Bottle environment variables:
 WINEESYNC -> 1
Exec-ing '/opt/cxoffice/bin/cxupdatecheck' '--reminder'
Exec-ing '/opt/cxoffice/bin/cxrating' '--bottle' 'nine' '--reminder'

** Sat Jul  3 21:29:35 2021
Starting '/opt/cxoffice/bin/wineloader' 'winewrapper.exe' '--new-console' '--workdir' 'C:\users\crossover\Start Menu' '--start' '--'
'C:\users\crossover\Start Menu\Oblivion.lnk'

Environment:
  CX_ROOT = "/opt/cxoffice"
  CX_BOTTLE = "nine"
  WINEPREFIX = "/home/io/.cxoffice/nine"
  CX_WINDOWS_VERSION = <undefined>
  PATH = "/opt/cxoffice/bin:/home/io/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
  LD_LIBRARY_PATH = "/opt/cxoffice/lib64:/opt/cxoffice/lib"
  WINEDLLPATH = "/opt/cxoffice/lib/wine"
  WINEDLLOVERRIDES = <undefined>
  LD_PRELOAD = <undefined>
  LD_ASSUME_KERNEL = <undefined>
  WINELOADER = "/opt/cxoffice/bin/wineloader"
  WINESERVER = "/opt/cxoffice/bin/wineserver"
  WINEDEBUG = <undefined>
  CX_LOG = "-"
  CX_DEBUGMSG = <undefined>
  DISPLAY = ":0.0"
  VKD3D_DEBUG = <undefined>
  VKD3D_SHADER_DEBUG = <undefined>
2173: Releasing the '/tmp/.wine-1000/bottle-805-142b4b.lock' lock
Command:
/opt/cxoffice/bin/wineloader winewrapper.exe --new-console --workdir C:\users\crossover\Start Menu --start -- C:\users\crossover\Start Menu\Oblivion.lnk
esync: up and running.
reading '/opt/cxoffice/etc/cxoffice.conf' took 0.0013s
reading '/home/io/.cxoffice/cxoffice.conf' took 0.0003s
2175: Grabbing the '/tmp/.wine-1000/cxoffice.conf.lock' lock
reading '/home/io/.cxoffice/cxoffice.conf' took 0.0000s
'/home/io/.cxoffice/cxoffice.conf' not modified -> no need to save

2175: Releasing the 'cxoffice.conf' lock
reading '/opt/cxoffice/etc/cxoffice.conf' took 0.0010s
reading '/home/io/.cxoffice/cxoffice.conf' took 0.0002s
reading '/home/io/.cxoffice/nine/cxbottle.conf' took 0.0007s
Found no application to rate in nine
0034:fixme:font:opentype_enum_font_names handle name format 1
0034:fixme:font:opentype_enum_font_names handle name format 1
0034:fixme:font:opentype_enum_font_names handle name format 1
0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0068:fixme:font:opentype_enum_font_names handle name format 1
0068:fixme:font:opentype_enum_font_names handle name format 1
0068:fixme:font:opentype_enum_font_names handle name format 1
0070:fixme:font:opentype_enum_font_names handle name format 1
0070:fixme:font:opentype_enum_font_names handle name format 1
0070:fixme:font:opentype_enum_font_names handle name format 1
0060:fixme:font:opentype_enum_font_names handle name format 1
0060:fixme:font:opentype_enum_font_names handle name format 1
0060:fixme:font:opentype_enum_font_names handle name format 1
0068:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0068:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0070:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0070:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0060:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0060:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
002c:fixme:font:opentype_enum_font_names handle name format 1
002c:fixme:font:opentype_enum_font_names handle name format 1
002c:fixme:font:opentype_enum_font_names handle name format 1
002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:fixme:font:opentype_enum_font_names handle name format 1
0024:fixme:font:opentype_enum_font_names handle name format 1
0024:fixme:font:opentype_enum_font_names handle name format 1
0024:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:fixme:exec:SHELL_execute flags ignored: 0x00000100
00fc:fixme:font:opentype_enum_font_names handle name format 1
00fc:fixme:font:opentype_enum_font_names handle name format 1
00fc:fixme:font:opentype_enum_font_names handle name format 1
00fc:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
00fc:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:fixme:exec:SHELL_execute flags ignored: 0x00004100
0114:fixme:font:opentype_enum_font_names handle name format 1
0114:fixme:font:opentype_enum_font_names handle name format 1
0114:fixme:font:opentype_enum_font_names handle name format 1
0114:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0114:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0114:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
[1;32mNative Direct3D 9 v0.8.0.385-release is active.
For more information visit https://github.com/iXit/wine-nine-standalone[0m
[1;32mNative Direct3D 9 v0.8.0.385-release is active.
For more information visit https://github.com/iXit/wine-nine-standalone[0m
fixme:d3d9nine:DRIPresentGroup_GetMultiheadCount (0x192a98), stub!
fixme:d3d9nine:DRIPresentGroup_GetMultiheadCount (0x192a98), stub!
0114:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x230 for device 0.
0114:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.

Thanks in advance for your help and have a nice day

Best Regards

**Comment by CTRL-ALT-DEL-92** [comment]
Good News latest libd3dadapter9 update fixed the issue 
![oblivion](https://user-images.githubusercontent.com/78966095/124380509-36b9ad80-dcbd-11eb-943c-eec2fa754f7c.png)

**Comment by CTRL-ALT-DEL-92** [comment]
The issue came back after latest oibaf ppa update...

**Comment by lorn10** [comment]
I was able to generate an apitrace, - maybe this problem can be fixed in the near feature. :+1: 

By the way, it's really nice to see that Gallium Nine is even working also at such quite old Intel Ironlake hardware. I am at an Apple iMac 12,2 computer which is a hybrid GPU system. It contains an Intel Sandy Bridge iGPU and an AMD TURKS Radeon HD 6770M. But until now I was not able to activate the new Crocus Gallium 3D driver. Can you please paste the output of:

`LIBGL_DEBUG=verbose glxinfo | grep direct`

`glxinfo -B`

Thanks!

**Comment by CTRL-ALT-DEL-92** [comment]
Hi,

As you requested here is the output of Libgl_debug:libGL: Can't open configuration file /usr/local/etc/drirc: No such file or directory.
libGL: Warning in /home/io/.drirc line -1, column -1: <option> should be inside <application>.
libGL: using driver i915 for 4
libGL: Can't open configuration file /usr/local/etc/drirc: No such file or directory.
libGL: Warning in /home/io/.drirc line -1, column -1: <option> should be inside <application>.
libGL: MESA-LOADER: dlopen(/usr/local/lib/x86_64-linux-gnu/dri/crocus_dri.so)
libGL: Can't open configuration file /usr/local/etc/drirc: No such file or directory.
libGL: Warning in /home/io/.drirc line -1, column -1: <option> should be inside <application>.
libGL: Can't open configuration file /usr/local/etc/drirc: No such file or directory.
libGL: Warning in /home/io/.drirc line -1, column -1: <option> should be inside <application>.
libGL: Can't open configuration file /usr/local/etc/drirc: No such file or directory.
libGL: Warning in /home/io/.drirc line -1, column -1: <option> should be inside <application>.
libGL: Using DRI3 for screen 0
direct rendering: Yes
    GL_EXT_demote_to_helper_invocation, GL_EXT_direct_state_access, 



Here's the output of glxinfo -B:

name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) HD Graphics (ILK) (0x46)
    Version: 21.2.0
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 2.0
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics (ILK)
OpenGL version string: 2.1 Mesa 21.2.0-devel
OpenGL shading language version string: 1.20

OpenGL ES profile version string: OpenGL ES 2.0 Mesa 21.2.0-devel
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16


On phoronix I read that a new extension will be added to crocus so even this old hardware can support glsl 1.30. This means a veri basic dx10 ten support.

**Comment by lorn10** [comment]
Thanks! Interesting, Crocus Gallium is working despite the many `No such file or directory` errors. So this type of error has no effect regarding the functionality of Crocus, it is in fact irrelevant. I have to search regarding may "Crocus not loading" problem somewhere else.

Yes, yours 5th generation Intel iGPU is in terms of 3D API support really a somewhat special one. It has some **DX10** features but is limited otherwise to **OpenGL 2.x**. Maybe the Mesa devs can add partial OpenGL 3.x but the performance will be not as great because some functions must be emulated. The 6th generation iGPU (aka Sandy Bridge) was the first real DX10.1 GPU from Intel and it has also rock solid OpenGL 3.3 support on Linux and Mac OS (but not Windows).

**Comment by axeldavy** [comment]
The issue might be a duplicate of https://github.com/iXit/wine-nine-standalone/issues/111

**Comment by CTRL-ALT-DEL-92** [comment]
Thank you all for your hard work now the game works like a  charm.  YOU ROCK!!!!!!
