### ISSUE TITLE
Freesync support

### ISSUE THREAD

**Issue by axeldavy** [iXit/wine-nine-standalone#14]
Moving this bug there:
https://github.com/iXit/Mesa-3D/issues/286

There is need to set a property similar to what we did for _NET_WM_BYPASS_COMPOSITOR.
See the mesa glx to see what to do.

**Comment by mkaito** [comment]
Hi!

Once this #17 is in a release, we should `export _VARIABLE_REFRESH=1` to enable freesync, correct?

**Comment by dhewg** [comment]
No, its not an env var. It will work automagically if your X11 is set up for VRR (which is `Option "VariableRefresh" "on"`` for amdgpu atm)
