### ISSUE TITLE
Gallium Nine (winetricks) seems to be broken since Wine 8.3

### ISSUE THREAD

**Issue by lorn10** [iXit/wine-nine-standalone#149]
Hi all

Unfortunately it happened again. It really looks that Gallium Nine (installed via winetricks) is broken in **Wine 8.3** devel.

When I start a d3d9 application like the CXBX-R Xbox emulator then I get on the CLI:
```
0024:err:module:import_dll Loading library d3d9.dll (which is needed by L"Z:\\home\\urs\\Downloads\\Cxbx\\2022\\cxbx.exe") failed (error c000012f).
0024:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\urs\\Downloads\\Cxbx\\2022\\cxbx.exe" failed, status c0000135
```

This worked normally in Wine 8.2 (and earlier).

**Comment by dhewg** [comment]
We just switched the CI setup to ubuntu 20.04, so the builds are compiled with a more recent WINE.
Does the build attached here work?
https://github.com/iXit/wine-nine-standalone/actions/runs/4337549042

**Comment by dhewg** [comment]
v8.3 removed libwine, and our releases link to it. winegcc of the version we used to build a releases automatically links it tough.
Ignore the version above, here're two, please give each one a spin:
https://github.com/dhewg/wine-nine-standalone/actions/runs/4343698597
I guess 20.04 doesn't work and 22.04 does?

**Comment by lorn10** [comment]
Really sorry to say this, - I am just a more "technical interested" end-user with no compiling experiences. :wink: 

Yes, I am on Kubuntu **22.04 LTS** and I am also using the **[oibaf PPA](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers)** (which includes latest Mesa devel Gallium Nine).

Currently installed is: Mesa 23.1.0-devel (git-0d8a54f 2023-03-06 jammy-oibaf-ppa)

Gallium Nine is installed trivially via `winetricks galliumnine`.

**Comment by dhewg** [comment]
np, you don't have to compile anything. There're two downloadable "Artifacts" in that last link. Those are binaries, please test each

**Comment by dhewg** [comment]
Alright, I assume the 20.04 version doesn't work just as the latest version from winetricks?

**Comment by dhewg** [comment]
For the details I have opened https://bugs.winehq.org/show_bug.cgi?id=54635
Let's see if that can be fixed for WINE or if we have to handle that

**Comment by lorn10** [comment]
Great, - will test the 20.04 build today evening at my **20.04 LTS** iMac computer. :+1:

**Comment by dhewg** [comment]
Sorry, I meant to try the 20.04 build on your 22.04 Kubuntu. It's just on what distro/wine version this was built. The issue is related to specific versions.

**Comment by lorn10** [comment]
Okay, I have tried it at a different prefix with the **20.04** package and I am getting:

```
test@iMac-tmp:~/gallium-nine-standalone$ WINEPREFIX=~/.wine ./nine-install.sh
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
installing 32bit binaries to /home/test/.wine/dosdevices/c:/windows/syswow64
installing 64bit binaries to /home/test/.wine/dosdevices/c:/windows/system32
enabling gallium nine
wine: failed to start L"C:\\windows\\system32\\ninewinecfg.exe"
wine: failed to start L"C:\\windows\\system32\\ninewinecfg.exe"
Es konnte keine Anwendung gestartet werden, oder es ist keine Anwendung mit der angegebenen Datei verknüpft.
ShellExecuteEx fehlgeschlagen: Datei nicht gefunden.
```

While the 22.04 variant is working. :+1:

**Comment by dhewg** [comment]
Alright, as suspected. Thanks for the confirmation!

**Comment by toni-klimaks** [comment]
> Okay, I have tried it at a different prefix with the **20.04** package and I am getting:
> 
> ```
> test@iMac-tmp:~/gallium-nine-standalone$ WINEPREFIX=~/.wine ./nine-install.sh
> 007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
> 007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
> 007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
> 007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
> installing 32bit binaries to /home/test/.wine/dosdevices/c:/windows/syswow64
> installing 64bit binaries to /home/test/.wine/dosdevices/c:/windows/system32
> enabling gallium nine
> wine: failed to start L"C:\\windows\\system32\\ninewinecfg.exe"
> wine: failed to start L"C:\\windows\\system32\\ninewinecfg.exe"
> Es konnte keine Anwendung gestartet werden, oder es ist keine Anwendung mit der angegebenen Datei verknüpft.
> ShellExecuteEx fehlgeschlagen: Datei nicht gefunden.
> ```
Hello.
I am getting the same message. When installing the binary version. (nine-install.sh)
Does it look like it's working?
> ```
> enabling gallium nine
> ```
But I can't login to the GUI.
> ```
> wine: failed to start L"C:\\windows\\system32\\ninewinecfg.exe"
> Es konnte keine Anwendung gestartet werden, oder es ist keine Anwendung mit der angegebenen Datei verknüpft.
> ShellExecuteEx fehlgeschlagen: Datei nicht gefunden.
> ```
It does not matter if it works, but I would like to understand why this error occurs and how to fix it.

**Comment by dungeon007** [comment]
Probably binary is better to have one LTS and one RNR versions.
So users of stable WINE versions to use LTS... and Rock 'n' Roll for else, he, he :D 
But lets hope if backward compat could be fixed somehow wont be broken, and to not need to run into that. 
I guess if Ubuntu 20.04 and Debian 11 do not default to WINE 5, but to 6... then this shouldnt be a biggie, so just make a new binary requiring WINE 6 or up and so be it.

**Comment by lorn10** [comment]
@toni-klimaks 
When you are on **Wine 8.3** you can use the 22.04 named build, - even if you use (K)Ubuntu 20.04 LTS. :wink:

**Comment by dhewg** [comment]
But then we might have different problems, as a binary build with a newer WINE won't work on an older WINE.

**Comment by dhewg** [comment]
> I guess you can built one even against WINE 2 that works on WINE 8 isnt it?

Up to 8.2, 8.3 obviously not anymore

And if possible I'd like to keep the "one binary works everywhere" approach, I'm looking at possible hacks atm

**Comment by dhewg** [comment]
Can you guys please test if this build ("Artifact") works for you?
https://github.com/dhewg/wine-nine-standalone/actions/runs/4365790268

Does someone have WINE v5.0 to check if it works there?

**Comment by dungeon007** [comment]
Why 5 when i have 4, just WINE 4.0.4 32bit. so:
`$ ./nine-install.sh 
installing 32bit binaries to /home/me/.wine/dosdevices/c:/windows/system32
wine64 not found, skipping 64bit
enabling gallium nine
err:d3d9nine:__wine_dll_register registering DLL for WINE backwards compatibility
err:d3d9nine:__wine_dll_register registering DLL for WINE backwards compatibility`
 It kind of erroring out there, but GUI behave OK and games actually working OK too.
`$ wine ninewinecfg
err:d3d9nine:__wine_dll_register registering DLL for WINE backwards compatibility
err:d3d9nine:__wine_dll_register registering DLL for WINE backwards compatibility
0009:fixme:win:EnumDisplayDevicesW ((null),0,0x32e794,0x00000000), stub!
0009:fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x32e794,0x00000000), stub!
0009:fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",1,0x32e794,0x00000000), stub!
0009:fixme:win:EnumDisplayDevicesW ((null),1,0x32e794,0x00000000), stub!
Native Direct3D 9 v0.9.0.395-devel is active.
For more information visit https://github.com/iXit/wine-nine-standalone`

**Comment by dhewg** [comment]
Ok, thanks! The `err:d3d9nine:__wine_dll_register registering DLL for WINE backwards compatibility` message is new, it's not an error, just something I added to confirm if that code is executed.
But there's another issue with those binaries on v8.3, let's see if that fixable...

**Comment by dhewg** [comment]
It's a tricky situation :\
Can you guys please give this build a spin? https://github.com/dhewg/wine-nine-standalone/actions/runs/4371650304
Please try to test that against older WINE versions!

**Comment by dungeon007** [comment]
Now the opposite of yesterday. Works on 8.3, fails on 4.0.4 with:

> $ ./nine-install.sh 
installing 32bit binaries to /home/me/.wine/dosdevices/c:/windows/system32
wine64 not found, skipping 64bit
enabling gallium nine
wine: Bad EXE format for C:\windows\system32\ninewinecfg.exe.

 One breaks newer, other breaks older... so :D

**Comment by dhewg** [comment]
I don't like any of that option because that's just too much bending over for what?
If we don't find a way to extend the compatibility, the next version will just be for WINE >=v5.7. For older versions one can always use the current version.
I think that should work for everybody?

**Comment by dungeon007** [comment]
Well, i saw that Ubuntu 18.04 also have 8.3 in WINE repos... so that is why i started to think this way.
But if that is not supported, then OK, you can do build with higher glibc req.

**Comment by dhewg** [comment]
18.04 will be unsupported in ~3 weeks as CI, so that's out of the picture anyway.

So you need 20.04 for the next v0.9 in any case as that's going to be binary incompatible for older distros.
One can use v0.8 for older distros. Same for WINE <v5.7.
22.04 is the current LTS, which is ~1year old. With that v0.9 will work with just the ubuntu wine package.

And all of that is just specific to the binary releases here. Building from source works everywhere.

Sounds okay to me?

**Comment by dungeon007** [comment]
Yep, sometimes things does not match everywhere.
Sure building source is OK, we are just talking about binary to serve them all versions and i guess all users, minus some, time :D

**Comment by dhewg** [comment]
I confirmed that this build https://github.com/dhewg/wine-nine-standalone/actions/runs/4373801118 works on v5.7 but not on v5.6.  And it works on v8.3.

@lorn10 & @toni-klimaks can you please test if that version works for you?
It it does I'll push it and release it as v0.9

**Comment by lorn10** [comment]
This seems to work, - but with some strange messages which aren't present at the 22.04 labeled build:

```
tmp@iMac-tmp:~/gallium-nine-standalone$ WINEPREFIX=~/.test_g9install ./nine-install.sh
wine: created the configuration directory '/home/tmp/.test_g9install'
002c:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
0048:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
0050:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
0050:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0050:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0050:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0050:err:ole:start_rpcss Failed to open RpcSs service
0048:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
0048:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
0048:err:ole:apartment_get_local_server_stream Failed: 0x80004002
0048:fixme:imm:ImeSetActiveContext (000000000001002E, 0): stub
0048:fixme:imm:ImmReleaseContext (0000000000010020, 000000000001002E): stub
002c:fixme:imm:ImeSetActiveContext (0000000000010056, 1): stub
002c:fixme:imm:ImmReleaseContext (0000000000010054, 0000000000010056): stub
0094:fixme:file:NtLockFile I/O completion on lock not implemented yet
0094:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
009c:fixme:file:NtLockFile I/O completion on lock not implemented yet
009c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
00ac:fixme:imm:ImeSetActiveContext (00000000000100A8, 1): stub
00ac:fixme:imm:ImmReleaseContext (000000000002009C, 00000000000100A8): stub
009c:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
009c:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
0094:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
0094:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
0108:fixme:msg:pack_message msg 14 (WM_ERASEBKGND) not supported yet
0134:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0134:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0134:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
wine: configuration in L"/home/tmp/.test_g9install" has been updated.
0134:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
installing 32bit binaries to /home/tmp/.test_g9install/dosdevices/c:/windows/syswow64
installing 64bit binaries to /home/tmp/.test_g9install/dosdevices/c:/windows/system32
enabling gallium nine
done
```

**Comment by lorn10** [comment]
Yeah, my fault sorry. It looks that I have made a typing error and the above output is because there was established a new prefix while gallium nine was installed on the same time.

This is the output when the wine prefix is already present:
```
test@iMac-tmp:~/gallium-nine-standalone$ WINEPREFIX=~/.g9install ./nine-install.sh
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0084:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
installing 32bit binaries to /home/test/.g9install/dosdevices/c:/windows/syswow64
installing 64bit binaries to /home/test/.g9install/dosdevices/c:/windows/system32
enabling gallium nine
done
```

Everything okay! :+1:

**Comment by dhewg** [comment]
Released:
https://github.com/iXit/wine-nine-standalone/releases/tag/v0.9

**Comment by dhewg** [comment]
winetricks PR which handles the incompatibilities: https://github.com/Winetricks/winetricks/pull/2044

**Comment by dhewg** [comment]
Should all be fixed then
