### ISSUE TITLE
v0.9 build failure on Gentoo ~amd64

### ISSUE THREAD

**Issue by CNR0706** [iXit/wine-nine-standalone#167]
Hi there! When trying to build gallium-nine-standalone from source either manually or using emerge I encounter this build failure:

```
FAILED: d3d9-nine/d3d9-nine.dll.so.p/present.c.o
winegcc -Id3d9-nine/d3d9-nine.dll.so.p -Id3d9-nine -I../../../home/cnr07/Documents/builds/wine-nine-standalone/d3d9-nine -I/usr/include/libdrm -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O3 -U_WIN32 -U__WIN32 -U__WIN32__ -U__WINNT -U__WINNT__ -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN '-DDECLSPEC_HOTPATCH=__attribute__((__ms_hook_prologue__))' '-DNINE_VERSION="v0.9.0.396-release"' '-DNINE_URL="https://github.com/iXit/wine-nine-standalone"' -DD3D9NINE_DRI2=1 '-DD3D9NINE_MODULEPATH="/usr/lib64/d3d"' -m64 -fPIC -MD -MQ d3d9-nine/d3d9-nine.dll.so.p/present.c.o -MF d3d9-nine/d3d9-nine.dll.so.p/present.c.o.d -o d3d9-nine/d3d9-nine.dll.so.p/present.c.o -c ../../../home/cnr07/Documents/builds/wine-nine-standalone/d3d9-nine/present.c
In file included from ../../../home/cnr07/Documents/builds/wine-nine-standalone/d3d9-nine/present.c:26:
../../../home/cnr07/Documents/builds/wine-nine-standalone/d3d9-nine/present.c: In function ‘present_has_d3dadapter’:
../../../home/cnr07/Documents/builds/wine-nine-standalone/d3d9-nine/present.c:1774:24: error: implicit declaration of function ‘XrmUniqueQuark’ [-Wimplicit-function-declaration]
 1774 |     d3d_hwnd_context = XUniqueContext();
      |                        ^~~~~~~~~~~~~~
winegcc: /usr/bin/x86_64-pc-linux-gnu-gcc failed
```

My GCC version is: ```gcc version 14.1.1 20240516 (Gentoo 14.1.1_p20240518 p1)```

Relevant env vars:
```WARNING_FLAGS=""```
```COMMON_FLAGS="-march=native -O2 -pipe"```
```CFLAGS="${COMMON_FLAGS}"```
```CXXFLAGS="${COMMON_FLAGS}"```
```FCFLAGS="${COMMON_FLAGS}"```
```FFLAGS="${COMMON_FLAGS}"```

Full logs (Manual): https://pastebin.com/7MiHwbj8
Full logs (Emerge): https://pastebin.com/6Zt9tpw2
(The compile flags were different during that run, however the error didn't change)

Sorry if there is some missing information. I only know the bare basics when it comes to the process of building software so I don't really know what information is relevant and what isn't.

If any further information is required I'll try to provide it ASAP.

**Comment by dhewg** [comment]
Pushed a fix to the main branch, does that work for you?

**Comment by CNR0706** [comment]
Issue resolved! Thank you :D

![image](https://github.com/iXit/wine-nine-standalone/assets/133519510/2e6092d4-53e8-444c-8fe8-b5cc7ab2bc08)
