### ISSUE TITLE
WINE 9.18 break

### ISSUE THREAD

**Issue by dungeon007** [iXit/wine-nine-standalone#173]
**wine ninewinecfg
err:d3d9nine:get_wine_drawable_from_dc Unexpected error in X Drawable lookup (hdc=0x47010066)
err:d3d9nine:d3dadapter9_new No available native adapters in system.**

Probably some of these at: https://gitlab.winehq.org/wine/wine/-/commits/wine-9.18/dlls/winex11.drv?ref_type=tags , so lets bisect this... 

 Yep, it is about that one **winex11: Implement offscreen window presents with NtGdiStretchBlt.** https://gitlab.winehq.org/wine/wine/-/commit/e8455e48d40597f0362792d71313717fe04b58a7

 Maybe i shouldnt jump on every development prerelease perversions... preversions, maybe they will fix it further maybe not... i cannot be sure in that, if nothing at least a note.

**Comment by dhewg** [comment]
Yeah, the struct size changed with that commit.

But that's on us because we use WINE interal stuff.
Does the attached patch fix it?

**Comment by dhewg** [comment]
[0001-d3d9-nine-support-WINE-9.19-s-X11DRV_GET_DRAWABLE.patch.txt](https://github.com/user-attachments/files/17173743/0001-d3d9-nine-support-WINE-9.19-s-X11DRV_GET_DRAWABLE.patch.txt)

**Comment by dungeon007** [comment]
Yep, that works, before and after. Didnt tested going down to that v8.3, but i guess it should.

**Comment by dhewg** [comment]
Okay, thanks!

Let's wait for the 9.19 release, if that code stays as it is right now, 
I'll commit the patch.

Since I'm not using anything wine/nine atm, please let me know once it's 
out ;)

**Comment by dungeon007** [comment]
> please let me know once it's out ;)
Well it is easy to guess when, in about a week time. As WINE releases are bi-weekly and usually seems made at friday, so 9.19 is expected to be there at about next friday.

**Comment by dungeon007** [comment]
@dhewg 
 9.19 released, problem stays... lets go :dancers:

**Comment by dhewg** [comment]
So the patch still fixes the issue with 9.19 final?

**Comment by dungeon007** [comment]
Yeah, patch makes it working on WINE 9.18 and 9.19

**Comment by dhewg** [comment]
Alright, pushed!

Thanks for the report, testing and confirmation ;)

**Comment by dhewg** [comment]
Could you please test this binary build from CI (the build artifact link at the bottom)?
https://github.com/iXit/wine-nine-standalone/actions/runs/11200279076
If that works with 9.19 and <9.18 we could do a release

**Comment by dungeon007** [comment]
@dhewg
 Sure thing, will do some huge tests up and down around WINE versions... maybe in a hour or so.

 So let start :dagger: 
WINE 9.19 - WORKS
![9 19](https://github.com/user-attachments/assets/c28308c2-9360-42e9-b31d-d6aef4015d07)

WINE 9.17 - WORKS
![9 17](https://github.com/user-attachments/assets/458db60b-2a20-47f0-b713-978793087611)

WINE 9.0 - WORKS
![9 0](https://github.com/user-attachments/assets/ff20df0f-e7ba-44fb-bc23-3a6b4f0c3a5e)

WINE 8.0.2 - WORKS
![8 0 2](https://github.com/user-attachments/assets/37fbf90e-fe4a-462f-b52e-1d9faafd676f)

WINE 7.0.2 - WORKS
![7 0 2](https://github.com/user-attachments/assets/38390a71-0076-4e7e-b3f8-eac476cc211d)

WINE 6.0.4 - WORKS
![6 0 4](https://github.com/user-attachments/assets/73478950-f031-4253-8960-d1e1baa2bb38)

WINE 5.0.5. - "WORKS" (if you build it from master against that version to get libwine support)
![5 0 5](https://github.com/user-attachments/assets/c55eeada-ba65-43dc-ab5e-92bfb89b7fcc)

WINE 4.0.4. - WORKS
![4 0 4](https://github.com/user-attachments/assets/5c9510e1-4835-4cd9-a1e9-e0d807e0db6f)

WINE 3.0.5 - WORKS (starts to dislike freetype there)
![3 0 5](https://github.com/user-attachments/assets/c0dfc2ce-994b-4051-a65b-d59b151c1a1a)

WINE 2.0.5 - WORKS (freetype again, not our problem anyway)
![2 0 5](https://github.com/user-attachments/assets/d978083b-ca49-400c-86b7-9dedf453b838)

As a bonus, lets go crazy there 🤣 skip 1.8.x, 1.6.x...they work too if you have right libs... so lets made it up for one of these ancient ones:
WINE 1.4.1. - WORKS
![1 4 1](https://github.com/user-attachments/assets/10492da1-6724-46aa-81ec-984c79684524)

 I mean, current master works even on 12/13 years old WINE 1.x versions, if you happen to have right libs around, if user know what he is doing, plus some luck, etc...or even 14/15 years, 1.x  is just for giggles really... one cant use that on a modern system 🤣
 
![1 2 3](https://github.com/user-attachments/assets/f78c1f35-8dfb-4c04-81f9-a1e5cb1d1401)
 
 So, yeah down compat looks good  :dancers:

**Comment by dungeon007** [comment]
>So, as a dumb end-user, what should I do?

Wait for release or if in hurry then grab latest artifact.

**Comment by dhewg** [comment]
> @dhewg Sure thing, will do some huge tests up and down around WINE versions... maybe in a hour or so.
> 
> So let start 🗡️ WINE 9.19 - WORKS
> WINE 9.17 - WORKS
> WINE 9.0 - WORKS
> WINE 8.0.2 - WORKS
> WINE 7.0.2 - WORKS
> WINE 6.0.4 - WORKS
> WINE 5.0.5. - "WORKS" (if you build it from master against that version to get libwine support)
> WINE 4.0.4. - WORKS
> WINE 3.0.5 - WORKS
> WINE 2.0.5 - WORKS
> As a bonus, lets go crazy there 🤣 skip 1.8.x, 1.6.x...they work too if you have right libs... so lets made it up for one of these ancient ones: WINE 1.4.1. - WORKS
> 
> I mean, current master works even on 12/13 years old WINE 1.x versions, if you happen to have right libs around, if user know what he is doing, plus some luck, etc...
> 
> So, yeah down compat looks good 👯

Wow, thanks alot, that's some nice archive of WINE versions!

**Comment by dhewg** [comment]
I just released v0.10, which includes this fix, thanks everybody!
