### ISSUE TITLE
Meson >= 0.46 not available on 18.04 ubuntu

### ISSUE THREAD

**Issue by montvid** [iXit/wine-nine-standalone#18]
Meson >= 0.46 not available on 18.04 ubuntu so it is impossible to compile. As it is supported for 5 years it would be nice the project supported it too.

> meson.build:3:0: ERROR: Meson version is 0.45.1 but project requires >= 0.46.

**Comment by dhewg** [comment]
You can use pip to install a fresh meson (per user too), it's what we do for our [travis builds](https://github.com/iXit/wine-nine-standalone/blob/master/.travis.yml#L70).
That's more practical than trying to make it work with old versions.

**Comment by montvid** [comment]
Thanks

**Comment by dhewg** [comment]
I assume that worked, did you build with the recent meson 0.50.0? Because that failed on travis for whatever reason...
