### ISSUE TITLE
0034:err:ninecfg:nine_set d3d9-nine.dll not found.

### ISSUE THREAD

**Issue by neowave2048** [iXit/wine-nine-standalone#2]
I get the error in the above title when running nine-install.sh with the pre-built binary release. ninewinecfg shows everything greyed out and only "loading of d3d0adapter9 succeeded," is checked. 64bit ninewinecfg shows everything is checked though. Is this normal? I'm on Ubuntu 18.04 with padoka stable mesa ppa and wine staging.

**Comment by WuShichao** [comment]
https://github.com/iXit/wine-nine-standalone/issues/1
Same problem on my desktop PC, but my laptop is OK.

**Comment by dhewg** [comment]
I ran into this on my notebook. Turns out the 32bit libegl library was missing. Can you check that?

**Comment by neowave2048** [comment]
@dhewg 
Checked and sure enough, it was missing like you said. Used `sudo apt-get install libegl1:i386` 
and ran 32bit ninewinecfg and all boxes are now checked. Thanks!

**Comment by dhewg** [comment]
Nice ;) FWIW I improved the messages about this situation already ;)

**Comment by dukenukemx** [comment]
> I ran into this on my notebook. Turns out the 32bit libegl library was missing. Can you check that?

Thank you @dhewg  that was also my problem.  I gotta bookmark this for future reference.

**Comment by dhewg** [comment]
But starting with v0.4 it shouldn't be required anymore to install the 32bit libegl. Only if you're actually using the DRI2 backend.
