### ISSUE TITLE
Steam overlay does not work.

### ISSUE THREAD

**Issue by ranomier** [iXit/wine-nine-standalone#22]
Hello,

i installed gallium-nine-standalone via winetricks inside of the game prefix and now the steam overlay is not working anymore.

Did i do something wrong, is there a known solution?

**Comment by axeldavy** [comment]
The steam overlay should work fine, except with proton, as only the gl overlay is available with it.

**Comment by ranomier** [comment]
uuh that was an fast answer! Thanks.

Yes im using it with proton? What alternatives are there?

**Comment by axeldavy** [comment]
The alternative is to have install steam (windows) in a wine prefix and install all your games from it. I assume proton's wine build can be used instead of system wine, if you need special proton workarounds.

**Comment by ranomier** [comment]
Does this work well with steam controller? Because i need the steam overlay for controller to work properly ...

**Comment by axeldavy** [comment]
I don't know, I have a steam controller, but I haven't played many games with it and I mapped it to a gamepad.

**Comment by ranomier** [comment]
https://github.com/popsUlfr/Proton/issues/3#issuecomment-450019901
This sounds interesting, is it realistic to do?

**Comment by axeldavy** [comment]
no, it is a lot of work

**Comment by ranomier** [comment]
I understand this :) Thanks anyway.

Steam inside WINE seems problematic with the controller. But thanks anyway :)
