### ISSUE TITLE
Graphical glitches in Dark Messiah of Might and Magic (apitrace included)

### ISSUE THREAD

**Issue by cyro666** [iXit/wine-nine-standalone#29]
Hi, me again. I swear, this is the last issue I found with Gallium Nine, everything else works.
There are some obvious graphical glitches in this game:
![mm2](https://user-images.githubusercontent.com/13151680/56455754-b704ca00-6362-11e9-972c-299a997494ad.png)
![mm3](https://user-images.githubusercontent.com/13151680/56455756-c421b900-6362-11e9-80df-414a13ff414c.png)

I had Gallium Nine active while recording this, so I hope that is ok.
Here's the trace:
https://drive.google.com/open?id=1PssHdGzoOpbHBdGk003zoq7ofGKM4KfY

**Comment by axeldavy** [comment]
Thanks, trace replays the issue, we'll take a look.

**Comment by axeldavy** [comment]
Apitrace is not totally friendly with msaa it seems. The rendertarget doesn't show.

Could you make a new trace with aliasing off ?

**Comment by cyro666** [comment]
I wanted to do it, but it seems the latest windows release apitrace doesn't include dlls anymore? I followed the link in your wiki, but under `x86/lib/wrappers` all I had was some `.pdb` files.

**Comment by cyro666** [comment]
Here it is:
https://drive.google.com/open?id=1aXl3282491NuIu7RKoCOOIlJ5P2DHG2k
