### ISSUE TITLE
Brawlhalla screen is offset

### ISSUE THREAD

**Issue by FaithLV** [iXit/wine-nine-standalone#3]
Hey!

I'm trying to run [Brawlhalla](https://store.steampowered.com/app/291550/Brawlhalla/), but with galium-nine enabled, screen seems to render offset. Mouse is still detected where it should be.

Wine: 4.0 Staging
Driver:  X.Org AMD Radeon (TM) R9 380 Series (TONGA, DRM 3.27.0, 4.20.6-zen1-1-zen, LLVM 7.0.1)
Driver Version:  4.5 (Compatibility Profile) Mesa 18.3.3

Screenshots:
![](https://i.imgur.com/mkGtpeg.png)
![](https://i.imgur.com/wNdRgqh.png)

**Comment by axeldavy** [comment]
Do you have the same issue if using the virtual desktop mode (see winecfg) ?

**Comment by dhewg** [comment]
Please attach a log with nine enabled: `WINEDEBUG=d3d9nine wine $game 2>&1 | tee nine.log`

Does it work with nine disabled?

**Comment by FaithLV** [comment]
Yes, it does work with nine disabled, but performance is subpar.
Yes, it does seem to work in virtual desktop mode.

The log:  (without virtual desktop)
https://gist.github.com/FaithLV/4a1572c01f76dc9ba673085f4cf4f2ae

**Comment by dhewg** [comment]
Did you compile this project yourself?

**Comment by FaithLV** [comment]
Compiled from this: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gallium-nine-git

**Comment by dhewg** [comment]
Ok nice. I pushed a test branch here https://github.com/iXit/wine-nine-standalone/commits/test
Can you try to make that aur build that? I think you just have to change it to
`source=("git+https://github.com/iXit/wine-nine-standalone.git#test")`
?

With that, do you get `ClientToScreen failed`? Does it work then?

**Comment by dhewg** [comment]
Oh, and do you have anything fancy on your X setup? Xwayland? dual gpu/monitor?

**Comment by FaithLV** [comment]
Hey, the test branch seems to be working fine!

Only fancy thing I have is dual monitor setup like this:
1280x1024, 1920x1080 (main)

**Comment by dhewg** [comment]
Ok, do you get that error mentioned above?
Does it still work if you build just with the first test commit:
`source=("git+https://github.com/iXit/wine-nine-standalone.git#f7c0dd65c669e9ca055c227cb6dd6ac6d9440386")` ?

**Comment by FaithLV** [comment]
Nope, didn't find anything like that in the log. 
Here's the log, just in case: https://gist.github.com/FaithLV/95f31b35733545aaede6631614d16fd4

Will try with first commit in just a sec.

**Comment by FaithLV** [comment]
Nope, doesn't seem to work without second commit.

Log: https://gist.github.com/FaithLV/cbd4711caf5399f09a7d6e7b58efe390

**Comment by dhewg** [comment]
````
DRI3Present_FillOffset Coord client area: 0 0
DRI3Present_FillOffset Coord drawable: 1280 0
DRI3Present_FillOffset Offset: -1280 0
````
The issue is related to the -1280, which matches the x res of your other display. I guess the 1920 display is to the right of the 1280 one? If you switch the right display to the left, does it work then?

**Comment by FaithLV** [comment]
You are correct and changing the monitor order works.

**Comment by dhewg** [comment]
I just updated the test branch, let's see if this fixes multi monitor setups.
Please test again with `#test` and post a log!

**Comment by FaithLV** [comment]
Yeah, it seems to be working.

**Comment by dhewg** [comment]
Hm nope, that patch is made of fail.
Could you please try again the just updated test branch? With log once more (which should we less spammy too) ;)
If that works, it'll land in master!

**Comment by FaithLV** [comment]
Yeah, that seems to work.

Here's the log: https://gist.github.com/FaithLV/06d117425d4b79ee0f521ca624f3e787

**Comment by dhewg** [comment]
Nice, but log is missing the relevant debug output using `WINEDEBUG=d3d9nine` :P

**Comment by FaithLV** [comment]
Whoops, sorry. This should be it.

https://gist.github.com/FaithLV/bb044431114aa997f0da8815258f871e

**Comment by dhewg** [comment]
Perfect, thanks!
Fix is now on master
