### ISSUE TITLE
Rayman Legends has horizontal banding

### ISSUE THREAD

**Issue by dukenukemx** [iXit/wine-nine-standalone#30]
I'm using Linux Mint 19.1 with Oibaf PPA and 0.4 wine-nine-standalone.  With Gallium Nine off you don't see any graphical issues but with it on you see these dark bands running horizontal.

**Comment by axeldavy** [comment]
We have known issues with Rayman and we have fixes such as this one:
https://github.com/iXit/Mesa-3D/commit/3b0dfed72699aa909b9c422ddfb62783749ca384

The fixes need some cleanup before being sent to mesa master.

**Comment by dhewg** [comment]
mesa 19.1 has this commit https://gitlab.freedesktop.org/mesa/mesa/commit/c097ff36174d77df9b641be392c5f15d4ab930fd

does the game work when you set the driconf var `dynamic_texture_workaround` (env var of the same name works too)?

**Comment by dhewg** [comment]
nevermind, the workaround is enabled for `Rayman Legends.exe` automatically, so it should just work (tm)
