### ISSUE TITLE
nine-install.sh fails from directory with space in the path

### ISSUE THREAD

**Issue by bniels707** [iXit/wine-nine-standalone#31]
Starting with a path such as `/home/nielsenb/space test/gallium-nine-standalone-v0.4/gallium-nine-standalone` causes the install to fail with `wine: cannot find L"C:\\windows\\system32\\ninewinecfg.exe"`

The error is caused by the produced symlinks being broken, an example broken symlink:

`testprefix/drive_c/windows/system32/ninewinecfg.exe -> '/home/nielsenb'$'\n''test/gallium-nine-standalone-v0.4/gallium-nine-standalone/bin64/ninewinecfg.exe.so'`

This is because the determination of `BASE` in `nine-install.sh` does not correctly account for spaces. Sticking with plain shell scripting, one potential workaround might be:

`BASE="$(dirname "$(readlink -f "$0")")"`

I can confirm this produces the correct symlink in both space and non-space cases.

**Comment by dhewg** [comment]
Thanks, fixed!
