### ISSUE TITLE
nineinstall.sh swaps 64 and 32 bit libraries

### ISSUE THREAD

**Issue by bniels707** [iXit/wine-nine-standalone#32]
A successful install produces the following:

`
installing 32bit binaries to /home/nielsenb/pathtest/gallium-nine-standalone-v0.4/gallium-nine-standalone/testprefix/dosdevices/c:/windows/syswow64
installing 64bit binaries to /home/nielsenb/pathtest/gallium-nine-standalone-v0.4/gallium-nine-standalone/testprefix/dosdevices/c:/windows/system32
enabling gallium nine
`

This appears backwards to me? The resulting install does appear to work from my quick testing.

**Comment by dhewg** [comment]
It's not backwards, and it matches a real windows install
