### ISSUE TITLE
err:ninecfg:nine_get removing dead symlink

### ISSUE THREAD

**Issue by Charadon** [iXit/wine-nine-standalone#36]
Been getting this issue since wine 4.8 came out, basically the checkbox in ninewinecfg doesn't work, and clicking it removes the symlink d3d9.dll thus  breaking all d3d9 games as they can't find the dll. Anyone else getting this issue?

**Comment by jcmolero** [comment]
me too, just running the ninewinecfg the symlinks are gone, so I had to do them manually, but not sure if I am pointing at the right files (d3d9.dll.so) but game has been running anyway

**Comment by z0z0z** [comment]
Also getting this.

**Comment by Espionage724** [comment]
Can also confirm this with Staging 4.8; but it works fine on 4.7 after downgrading to it.

**Comment by Charadon** [comment]
What's worse, is that I found that installing galliumnine through winetricks in a new prefix doesn't create the symlink at all.

**Comment by jcmolero** [comment]
> Can also confirm this with Staging 4.8; but it works fine on 4.7 after downgrading to it.

can you upload the symlinked d3d9.dll inside ~/.wine/drive_c/windows/system32/ please?

**Comment by Charadon** [comment]
@jcmolero d3d9.dll is supposed to symlink to d3d9-nine.dll in the same folder. Though, I don't think that matters since I don't think gallium-nine even works anymore in 4.8. Atleast it doesn't for me.

**Comment by axeldavy** [comment]
I guess wine will need to be bisected to find the fauly commit and understand the behaviour change.

**Comment by Charadon** [comment]
Wasn't wine replacing their direct3d9 renderer from OpenGL to Vulkan? If so, something they did could be the reason. But I feel like i'm mis-remembering.

**Comment by jcmolero** [comment]
> I guess wine will need to be bisected to find the fauly commit and understand the behaviour change.

in fact wine shows this everytime i run winecfg:
000d:err:menubuilder:init_xdg error looking up the desktop directory

**Comment by Charadon** [comment]
@jcmolero That has to do with your applications menu in your Desktop Environment. iirc

**Comment by jcmolero** [comment]
> @jcmolero That has to do with your applications menu in your Desktop Environment. iirc

yes, but in 4.7 has not shown, just after updating

**Comment by Charadon** [comment]
So, after doing some testing. I can confirm that gallium nine on 4.8 staging is completely broken. Applications that use Direct3d9 will just close instantly. The workaround was to downgrade back to 4.7

**Comment by jcmolero** [comment]
managed to downgrade to wine staging 3.7, checked the symlinks and actually they can be done in case of using 3.8:
ln -s /usr/bin/../lib32/wine/d3d9-nine.dll.so ~/.wine/drive_c/windows/syswow64/d3d9.dll
ln -s /usr/bin/../lib/wine/d3d9-nine.dll.so ~/.wine/drive_c/windows/system32/d3d9.dll

**Comment by Charadon** [comment]
@jcmolero I've done that, the issue is that, atleast for me, galliumnine just refuses to work on 4.8

**Comment by soredake** [comment]
https://bugs.winehq.org/show_bug.cgi?id=47160

**Comment by Charadon** [comment]
Oh sweet, so I should just wait until 4.9 before updating wine-staging again?

**Comment by axeldavy** [comment]
Nice finding, but then why is there report vanilla is affected too ? had it the same commit ?

**Comment by Myrddin-Wyllt** [comment]
@axeldavy Charadon neglected to mention that they were using Wine Staging, not Vanilla & I don't believe anyone else mentioned Vanilla; so this issue must lie with Wine Staging specifically.

Yes the OP didn't reveal their use of Staging until this comment:
> Oh sweet, so I should just wait until 4.9 before updating wine-staging again?

**Comment by Charadon** [comment]
@Myrddin-Wyllt Gah, I re-read my first post probably 5 times and failed to mention I was on staging. Sorry about that. If this is an issue with staging, then perhaps its time to close this issue?

**Comment by axeldavy** [comment]
Sure, please reopen if the problem comes back. Thanks for reporting and investigating.
