### ISSUE TITLE
Will be a deb installer for Ubuntu?

### ISSUE THREAD

**Issue by terrestrian** [iXit/wine-nine-standalone#4]
I am a Linux newbie. Compiling is just too complicated for me. I wonder if you make a deb installer for beginners?

**Comment by dhewg** [comment]
No .deb, but you can just grab the binary release here:
https://github.com/iXit/wine-nine-standalone/releases/tag/v0.2

And then follow the usage section in the README

**Comment by terrestrian** [comment]
I wasnt able to install in the first place. Check closed issues and found out that I dont have 32bit libegl library. see. #2. Succesfully installed now.
