### ISSUE TITLE
d3dadapter9.so.1 was not found on your system

### ISSUE THREAD

**Issue by montvid** [iXit/wine-nine-standalone#47]
I tried padoka ppa and oibaf ppa with no success running gallium nine on 4.10 wine staging ubuntu 18.04. Any tips?

**Comment by ImperatorS79** [comment]
Install the lib ? On ubuntu it is libd3dadapter9-mesa and libd3dadapter9-mesa:i386 ^^.

**Comment by montvid** [comment]
Thanks, it works now. Maybe a good idea to mention this in the readme? ubuntu does not come with thee libs by default.

**Comment by LyrixCaz** [comment]
Wow, thank you for this, maybe the error should have specified the i386 thing...
