### ISSUE TITLE
Vampire: The Masquerade – Bloodlines worse than wine dx9

### ISSUE THREAD

**Issue by montvid** [iXit/wine-nine-standalone#49]
Hi, does anyone have an idea what are these gallium nine errors about? They seem to have an impact on the fps count.

I use oibaf mesa 19.2 radeon rx580 on ubuntu 18.04.
With gallium nine I get 30 fps in open area:
```
Native Direct3D 9 v0.4.0.294-release is active.
For more information visit https://github.com/iXit/wine-nine-standalone
fixme:d3d9nine:DRIPresentGroup_GetMultiheadCount (0x166408), stub!
fixme:d3d9nine:DRIPresentGroup_GetMultiheadCount (0x166408), stub!
radeonsi: Forcing anisotropy filter to 16x
mesa: for the -simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the -global-isel-abort option: may only occur zero or one times!
```

With wined3d 40-60 fps in open area:

```
 0009:fixme:ver:GetCurrentPackageId (0x34e5a0 (nil)): stub
radeonsi: Forcing anisotropy filter to 16x
002c:fixme:d3d:state_linepattern_w Setting line patterns is not supported in OpenGL core contexts.
```

**Comment by montvid** [comment]
oh and wine 4.10

**Comment by Venemo** [comment]
Can you give us more information about your system? What kind of hardware do you have? Can you paste the output of `lshw` to a pastebin? Does the same issue happen when you run a stable mesa version?

**Comment by dhewg** [comment]
The wine warnings seem harmless.

This is from mesa though
> radeonsi: Forcing anisotropy filter to 16x

Sounds like you force that with an envar/driconf or something. Maybe that's the bottleneck? Game works fine here with nine.

**Comment by montvid** [comment]
Sorry I can't debug now not playing games for months. No time... thanks for checking!
