### ISSUE TITLE
Cannot build on debian 10

### ISSUE THREAD

**Issue by siyia2** [iXit/wine-nine-standalone#5]
creating /home/siyia/wine-nine-standalone-master/gallium-nine-standalone.tar.gz
additional meson args: 
found debian compatible distro
The Meson build system
Version: 0.49.2
Source dir: /home/siyia/wine-nine-standalone-master
Build dir: /tmp/tmp.JhveE0zw1Q/build64
Build type: cross build
Program tools/get_version.sh found: YES (/home/siyia/wine-nine-standalone-master/tools/get_version.sh)
Project name: Gallium Nine Standalone
Project version: 0.3.0.0-devel
Native C compiler: cc (gcc 8.2.0 "cc (Debian 8.2.0-20) 8.2.0")
Cross C compiler: winegcc (gcc 8.2.0)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program winegcc found: YES (/usr/bin/winegcc)
Checking if "winelib check" compiles: YES
Library wine found: YES
Has header "wine/debug.h" with dependency -lwine: YES
Program wrc found: YES (/usr/bin/wrc)
Checking for function "dlopen" : NO
Library dl found: YES
Checking for function "dlopen" with dependency -ldl: YES
Checking for function "dlclose" with dependency -ldl: YES
Checking for function "dlsym" with dependency -ldl: YES
Checking for function "dladdr" with dependency -ldl: YES
Cross dependency d3d found: YES 1.0.0
Cross dependency x11 found: YES 1.6.7
Cross dependency xext found: YES 1.3.3
Cross dependency x11-xcb found: YES 1.6.7
Cross dependency xcb found: YES 1.13.1
Cross dependency xcb-dri3 found: YES 1.13.1
Cross dependency xcb-present found: YES 1.13.1
Cross dependency xcb-xfixes found: YES 1.13.1
Cross dependency gl found: YES 18.3.2
Cross dependency egl found: YES 18.3.2
Message: DRI2 support is enabled
Library dxguid found: YES
Library uuid found: YES
Library advapi32 found: YES
Library gdi32 found: YES
Library user32 found: YES
Library shell32 found: YES
Library comctl32 found: YES
Library ole32 found: YES
Library shlwapi found: YES
Message: d3dadapter9.so.1 default module path: /usr/lib/x86_64-linux-gnu/d3d
WARNING: extract_all_objects called without setting recursive keyword argument. Meson currently defaults to non-recursive to maintain backward compatibility but the default will be changed in the future.
Build targets in project: 7
Option buildtype is: release [default: debugoptimized]
Found ninja-1.8.2 at /usr/bin/ninja
ninja: Entering directory `/tmp/tmp.JhveE0zw1Q/build64'
[17/18] Installing files.
Installing d3d9-nine/d3d9-nine.dll.so to /tmp/tmp.JhveE0zw1Q/gallium-nine-standalone/lib64
Installing d3d9-nine/d3d9-nine.dll.fake to /tmp/tmp.JhveE0zw1Q/gallium-nine-standalone/lib64
Installing ninewinecfg/ninewinecfg.exe.so to /tmp/tmp.JhveE0zw1Q/gallium-nine-standalone/bin64
Installing ninewinecfg/ninewinecfg.exe.fake to /tmp/tmp.JhveE0zw1Q/gallium-nine-standalone/bin64
The Meson build system
Version: 0.49.2
Source dir: /home/siyia/wine-nine-standalone-master
Build dir: /tmp/tmp.JhveE0zw1Q/build32
Build type: cross build
Program tools/get_version.sh found: YES (/home/siyia/wine-nine-standalone-master/tools/get_version.sh)
Project name: Gallium Nine Standalone
Project version: 0.3.0.0-devel
Native C compiler: cc (gcc 8.2.0 "cc (Debian 8.2.0-20) 8.2.0")
Cross C compiler: winegcc (gcc 8.2.0)
Host machine cpu family: x86
Host machine cpu: i686
Target machine cpu family: x86
Target machine cpu: i686
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program winegcc found: YES (/usr/bin/winegcc)
Checking if "winelib check" compiles: YES

meson.build:41:0: ERROR:  C library 'wine' not found

A full log can be found at /tmp/tmp.JhveE0zw1Q/build32/meson-logs/meson-log.txt

**Comment by dhewg** [comment]
Looks like missing 32bit dependencies, have a look [here](https://github.com/iXit/wine-nine-standalone/wiki/Debian-and-Ubuntu) for a list of required packages

**Comment by siyia2** [comment]
thx that did it!!!
