### ISSUE TITLE
Intel HD 4600 not detected 

### ISSUE THREAD

**Issue by TSnake41** [iXit/wine-nine-standalone#53]
* wine-4.14 (Staging)
* mesa 19.1.4
* GNOME with wayland 1.17
* wine-nine 0.4 (Arch Linux multilib)
* iGPU only setup (no discrete GPU)

On HD Graphics 4600, wine-nine doesn't detect driver.
`nine:drm_create_adapter Unable to load requested driver.
err:d3d9nine:present_create_adapter9 Unable to create ID3DAdapter9 (fd=13)
err:d3d9nine:d3dadapter9_new No available native adapters in system.`

Setting DRI_PRIME to 1 does make wine-nine detecting the device but performance suffers a lot (losing around 80% of performance in native games).

Possibly related to #46

**Comment by Venemo** [comment]
@TSnake41 If you want to use Gallium Nine on Intel, you need to use the iris driver which is currently not the default so you need to use an environment variable: `MESA_LOADER_DRIVER_OVERRIDE=iris` when you launch your game. This possibly won't work with mesa 19.1 - there was a bug in the iris driver which we fixed after the 19.1 release, so I recommend trying 19.2 (or if you are brave, latest mesa master) instead.

Let me now if this helps.

**Comment by Venemo** [comment]
Oh. I've just noticed that you have an Intel HD 4600. That is, as far as I see, 7th gen, so unfortunately, older than what the iris driver supports. For iris to work, you need 8th gen (Broadwell) or later. Chances are that you won't be able to use Gallium Nine on your HD 4600.

**Comment by Venemo** [comment]
I asked about it on IRC and here is the response:

```
[08:41:19] <jekstrand> Venemo: We're not pulling iris back to older hardware
[08:41:57] <jekstrand> Venemo: Iris' core design requires we have a decent size address space and we don't get 48-bit addresses until gen8
[08:42:20] <jekstrand> Venemo: Pulling it back to gen7 would be nuts and provide a lot of clutter that we don't want in a future-facing driver.
```

**Comment by dhewg** [comment]
Hardware doesn't have a gallium driver, there's nothing we can do here, so closing.
