### ISSUE TITLE
What's the next release's ETA?

### ISSUE THREAD

**Issue by Bryophyllum** [iXit/wine-nine-standalone#55]
Without https://github.com/iXit/wine-nine-standalone/commit/d9c516b8ff380bd3148aaae99757efa341393142 the latest official release doesn't search for d3dadapter library in the flatpak-specific paths and thus it can't be used with Flatpak Steam anymore. Previously, this was an issue only when using the beta release of Flatpak Steam, but, since a few days ago, it now affects users of the stable release, as freedesktop runtimes 19.08, which Gallium Nine Standalone is incompatible with, have been released on flathub, which marks them as a stable base to build Flatpaks on.

**Comment by dhewg** [comment]
Yeah, we need a new release! I'll look into it

**Comment by dhewg** [comment]
I just released v0.5 \o/
