### ISSUE TITLE
Darksiders II: Deathinitive Edition crashes when using wine-nine

### ISSUE THREAD

**Issue by Ahmed-E-86** [iXit/wine-nine-standalone#56]
**Darksiders II: Deathinitive Editio**n instantly crashes when using wine-nine with these errors messages:

```
Native Direct3D 9 v0.5.0.356-release is active.
For more information visit https://github.com/iXit/wine-nine-standalone
fixme:d3d9nine:DRIPresentGroup_GetMultiheadCount (0xe29f0), stub!
fixme:d3d9nine:DRIPresentGroup_GetMultiheadCount (0xe29f0), stub!
s 2 - Deathinitive Edition\Darksiders2.exe: ../src/gallium/state_trackers/nine/nine_pipe.h:247: d3d9_get_pipe_depth_format_bindings: Assertion `!"Unexpected format"' failed.
wine: Assertion failed at address 00007F0A6165DE97 (thread 002d), starting debugger...
```

### System Info:
CPU: I5 4200M
GPU: AMD HD 8750M
Driver: MESA 19.1.4
Wine-Staging 4.17
Wine-Nine-Standalone 0.5

**Comment by dungeon007** [comment]
I think there is some patch/es for this in ixit mesa:

https://github.com/iXit/Mesa-3D/issues/317

These are not part of regular mesa still... at least maybe you can test it to confirm.

**Comment by axeldavy** [comment]
I'm surprised it wasn't sent in mesa already.
Maybe I wanted to have some tests to check it is windows behaviour. I need to check.

**Comment by ahmed-elsayed2017** [comment]
I have never compiled MESA from source, and applying patches, so I am not encouraged to drag myself into that dark hole.

**Comment by ahmed-elsayed2017** [comment]
I use a little older version of MESA (X-Swat), because Padoka, and Obiaf PPAs are not stable. They broke my system multiple times.

**Comment by dhewg** [comment]
According to iXit/Mesa-3D#317 this should be fixed by:
https://gitlab.freedesktop.org/mesa/mesa/-/commit/5d904d27491aab489d54746bc6650b27c5927c39
