### ISSUE TITLE
Native Windows version

### ISSUE THREAD

**Issue by donizettilorenzo** [iXit/wine-nine-standalone#59]
Isn't it possible to have Gallium Nine as D3D9 to OpenGL wrapper on Windows too ?

**Comment by dhewg** [comment]
Nope, Gallium Nine maps D3D9 to mesa's internal gallium API, and not to OpenGL. There's D9VK, which maps D3D9 to Vulkan, and I think that works on Windows too?

**Comment by donizettilorenzo** [comment]
Of course D9VK is working!

**Comment by Venemo** [comment]
Mesa has Windows builds so it should be (theoretically) possible to use it.
