### ISSUE TITLE
nine standalone on wine tkg lutris

### ISSUE THREAD

**Issue by Meklahi** [iXit/wine-nine-standalone#6]
i am a newbie linux gamer, how to install nine standalone to wine tkg prefix in lutris app?

**Comment by dhewg** [comment]
In theory it should be easy: you just add standalone to a WINE prefix, doesn't really matter if its from lutris or not.
I don't use lutris myself, so I don't know how to do that. You could ask [here](https://forums.lutris.net/t/gallium-nine-standalone/4746).
Or you just open an issue for lutris to support standalone out of the box ;)

**Comment by dhewg** [comment]
There already is an issue: https://github.com/lutris/lutris/issues/1625

**Comment by dhewg** [comment]
And now I noticed that you opened that, d'oh ;)

**Comment by necrus7** [comment]
I have issue when trying to enable 32-bit gallium nine standalone via ninewinecfg on any wine 4.x package with this error: Couldn't load d3d9-nine.dll: L"Bad EXE format for %1.\r\n"
Meanwhile 64-bit library works great.

**Comment by dhewg** [comment]
That most likely means that a dependency isn't available. Check if you have the 32bit libEGL installed.

**Comment by necrus7** [comment]
Thanks, it helped. I just didn't find list of dependencies for binary builds.

**Comment by tuxutku** [comment]
can you send screenshots of your lutris settings so i can figure out what to do
i am very confused :(
it would be very helpful

**Comment by dhewg** [comment]
Initial support landed on lutris: lutris/lutris#2092
