### ISSUE TITLE
Any app or game

### ISSUE THREAD

**Issue by Pednick** [iXit/wine-nine-standalone#62]
wine-nine

When I put check mark in box for Enable Gallium Nine for better D3D9 graphic performance.

When I test it and run an app or game through console, it doesn't show the green text: Native Direct3D 9 v0.5.0.0-release is active.
For more information visit https://github.com/iXit/wine-nine-standalone

apparently meaning that it's not active.

I further checked, Permissions change from Group:user to Group:root for d3d9.dll

All this didn't happen when I run wine-staging-nine and everthing works normal through that.

I'm on Arch Linux btw.

**Comment by Pednick** [comment]
> wine-nine
> 
> When I put check mark in box for Enable Gallium Nine for better D3D9 graphic performance.
> 
> When I test it and run an app or game through console, it doesn't show the green text: Native Direct3D 9 v0.5.0.0-release is active.
> For more information visit https://github.com/iXit/wine-nine-standalone
> 
> apparently meaning that it's not active.
> 
> I further checked, Permissions change from Group:user to Group:root for d3d9.dll
> 
> All this didn't happen when I run wine-staging-nine and everthing works normal through that.
> 
> I'm on Arch Linux btw.

Just tried 0.2 and that one seems to work, shows green text: Native Direct3D 9 v0.2.0.166-release is active.
For more information visit https://github.com/iXit/wine-nine-standalone.

**Comment by dhewg** [comment]
Do you use arch packages or the releases found here https://github.com/iXit/wine-nine-standalone/releases?
If the former, do the latter work?

**Comment by Pednick** [comment]
> Do you use arch packages or the releases found here https://github.com/iXit/wine-nine-standalone/releases?
> If the former, do the latter work?

I tried both new versions, and they don't work.

**Comment by dhewg** [comment]
Independent of the version, where do the binaries you're using come from?

**Comment by Pednick** [comment]
> Independent of the version, where do the binaries you're using come from?

From the site you posted.

**Comment by dhewg** [comment]
Maybe you're missing a dependency. Do the arch packages work? https://www.archlinux.org/packages/multilib/x86_64/wine-nine/

**Comment by dhewg** [comment]
Actually, if you can enable it, it's active already. If you start ninewinecfg from a console, you should see that green text you mentioned.

**Comment by Pednick** [comment]
> Maybe you're missing a dependency. Do the arch packages work? https://www.archlinux.org/packages/multilib/x86_64/wine-nine/

Nope the arch package doesn't work as that's the first one I tried.

**Comment by Pednick** [comment]
> Actually, if you can enable it, it's active already. If you start ninewinecfg from a console, you should see that green text you mentioned.

Yes the green text works when running ninewinecfg but not when I test it with an app like dx9_initialization from https://wiki.ixit.cz/d3d9 it doesn't except on the earlier version.

**Comment by dhewg** [comment]
That sounds more like you're launching apps/games differently than ninewinecfg. Different prefix, or different envvars, something like that.

Please provide the output of `WINEDEBUG=d3d9nine wine ninewinecfg` and the output of a non-working app/game, also with `WINEDEBUG=d3d9nine`

**Comment by Pednick** [comment]
> That sounds more like you're launching apps/games differently than ninewinecfg. Different prefix, or different envvars, something like that.
> 
> Please provide the output of `WINEDEBUG=d3d9nine wine ninewinecfg` and the output of a non-working app/game, also with `WINEDEBUG=d3d9nine`

I not launching differently than ninewinecfg, different prefix, or different envvars. I will try what you suggested with WINEDEBUG and get back to you.

**Comment by Pednick** [comment]
I'm not at my linux station right now but will get back to you but I wanted to ask you if you've tried running an app and or game in console to see if the green activated text shows with 0.5v?

**Comment by Pednick** [comment]
You know what, nevermind I noticed it does show the green activated text if I launch the app directly from console just not when I launch it from wine explorer. I did however show the green text in the ealier version even through wine explorer and also when I install my saved version of the obsolete wine-staging-nine but never the less I will close this topic.

**Comment by dhewg** [comment]
You're right that it didn't show the status message when launching it from explorer. It was active and working though. I restored the old behavior on current master!

**Comment by Pednick** [comment]
> You're right that it didn't show the status message when launching it from explorer. It was active and working though. I restored the old behavior on current master!

Thank you.
