### ISSUE TITLE
Install_ESO.exe does not invoke with Galliumn Nine

### ISSUE THREAD

**Issue by Pednick** [iXit/wine-nine-standalone#63]
Install_ESO.exe does not invoke with Galliumn Nine enable, when disabled
it installs fine, not sure that should happen.

**Comment by Pednick** [comment]
> Install_ESO.exe does not invoke with Galliumn Nine enable, when disabled
> it installs fine, not sure that should happen.

Here's a WINEDEBUG=d3d9nine when Gallium Nine enabled:

WINEDEBUG=d3d9nine wine Install_ESO.exe
0009:fixme:ver:GetCurrentPackageId (0x326980 (nil)): stub
cwd: C:\users\lopov\Temp\I1575914697\Windows
cmd: "C:\users\lopov\Temp\I1575914697\Windows\resource\jre\bin\javaw.exe" -Xms16777216 -Xmx50331648 -Djava.specification.version=1.6 -Xmx512m -classpath "C:\users\lopov\Temp\I1575914697\InstallerData\IAClasses.zip;C:\users\lopov\Temp\I1575914697\InstallerData\Execute.zip;C:\users\lopov\Temp\I1575914697\Windows\InstallerData\Execute.zip;C:\users\lopov\Temp\I1575914697\InstallerData\Resource1.zip;C:\users\lopov\Temp\I1575914697\Windows\InstallerData\Resource1.zip;C:\users\lopov\Temp\I1575914697\InstallerData;C:\users\lopov\Temp\I1575914697\Windows\InstallerData;" com.zerog.lax.LAX "C:/users/lopov/Temp/I1575914697/Windows/setup.lax" "C:/users/lopov/Temp/lax325e.tmp" 
002e:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
002f:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
002f:fixme:font:freetype_SelectFont Untranslated charset 255
002f:fixme:dwmapi:DwmIsCompositionEnabled 0096ED60
trace:d3d9nine:Direct3DCreate9 sdk_version 0x20.
trace:d3d9nine:common_get_registry_string Getting string key 'ModulePath' at 'HKCU\Software\Wine\Direct3DNine'
trace:d3d9nine:common_get_registry_string Failed to open path 'HKCU\Software\Wine\Direct3DNine'
trace:d3d9nine:open_d3dadapter Trying to load '/usr/lib32/d3d/d3dadapter9.so.1'
trace:d3d9nine:open_d3dadapter Loaded '/usr/lib32/d3d/d3dadapter9.so.1'
trace:d3d9nine:present_has_d3dadapter d3dadapter9 version: 0.2
trace:d3d9nine:PRESENTCheckExtension PRESENT v1.0 found, v1.0 requested
trace:d3d9nine:backend_probe dpy=0x7d2274c0
trace:d3d9nine:dri3_probe DRI3 v1.0 found, v1.0 requested
trace:d3d9nine:backend_create dpy=0x7d2274c0 screen=0
trace:d3d9nine:dri3_probe DRI3 v1.0 found, v1.0 requested
trace:d3d9nine:backend_create Active backend: dri3
trace:d3d9nine:present_create_adapter9 Created ID3DAdapter9 with fd 74
Native Direct3D 9 v0.5.0.0-release is active.
For more information visit https://github.com/iXit/wine-nine-standalone
trace:d3d9nine:d3dadapter9_GetAdapterIdentifier DeviceName overriden: \\.\DISPLAY1
trace:d3d9nine:get_current_mode current mode 0 (1920x1080x32)
trace:d3d9nine:get_current_mode current mode 0 (1920x1080x32)
trace:d3d9nine:get_current_mode current mode 0 (1920x1080x32)
trace:d3d9nine:present_create_present_group Active present version: v1.4
trace:d3d9nine:present_create_present_group Returning 0x18da18
trace:d3d9nine:d3dadapter9_AddRef 0x18c9c0 increasing refcount to 2.
trace:d3d9nine:DRIPresentGroup_AddRef 0x18da18 increasing refcount to 2.
fixme:d3d9nine:DRIPresentGroup_GetMultiheadCount (0x18da18), stub!
fixme:d3d9nine:DRIPresentGroup_GetMultiheadCount (0x18da18), stub!
trace:d3d9nine:DRIPresent_AddRef 0x18d518 increasing refcount to 2.
trace:d3d9nine:DRIPresent_AddRef 0x18d518 increasing refcount to 3.
trace:d3d9nine:DRIPresent_SetPresentParameters This=0x18d518, params=0x7d8ed10, focus_window=0x10072, params->hDeviceWindow=0x10072
trace:d3d9nine:DRIPresent_SetPresentParameters Nothing changed.
trace:d3d9nine:dri3_window_buffer_from_dmabuf present_priv=0x18d6d0 dmaBufFd=80
trace:d3d9nine:dri3_window_buffer_from_dmabuf present_priv=0x18d6d0 dmaBufFd=80
trace:d3d9nine:DRIPresent_Release 0x18d518 decreasing refcount to 2.
trace:d3d9nine:DRIPresentGroup_Release 0x18da18 decreasing refcount to 1.
trace:d3d9nine:d3dadapter9_GetAdapterIdentifier DeviceName overriden: \\.\DISPLAY1
trace:d3d9nine:DRIPresent_AddRef 0x1c0648 increasing refcount to 2.
trace:d3d9nine:DRIPresent_SetPresentParameters This=0x1c0648, params=0x7d8ec94, focus_window=0x20082, params->hDeviceWindow=0x20082
trace:d3d9nine:DRIPresent_SetPresentParameters Nothing changed.
trace:d3d9nine:dri3_window_buffer_from_dmabuf present_priv=0x1bf890 dmaBufFd=93
trace:d3d9nine:DRIPresent_AddRef 0x1c0830 increasing refcount to 2.
trace:d3d9nine:DRIPresent_SetPresentParameters This=0x1c0830, params=0x7d8ec94, focus_window=0x20082, params->hDeviceWindow=0x20082
trace:d3d9nine:DRIPresent_SetPresentParameters Nothing changed.
trace:d3d9nine:dri3_window_buffer_from_dmabuf present_priv=0x1c09e8 dmaBufFd=99
trace:d3d9nine:dri3_window_buffer_from_dmabuf present_priv=0x1c09e8 dmaBufFd=99
trace:d3d9nine:PRESENTDestroyPixmapContent Releasing pixmap priv 0x1c0a70
trace:d3d9nine:get_d3d_drawable No d3d_drawable attached to hwnd 0x20082, creating one.
trace:d3d9nine:create_d3dadapter_drawable hwnd drawable: 52428805
trace:d3d9nine:get_drawable_offset Relative coord client area: (637,355)
trace:d3d9nine:offset_by_virtual_screen Virtual screen size: (0,0)-(1920,1080)
trace:d3d9nine:get_drawable_offset Coord client area: (637,355)
trace:d3d9nine:get_relative_position Next geometry: 1 38
trace:d3d9nine:get_relative_position Next geometry: 636 317
trace:d3d9nine:get_relative_position Successfully determined drawable pos (debug: 4220619, 1731, 1731)
trace:d3d9nine:get_drawable_offset Coord drawable: (637,355)
trace:d3d9nine:get_drawable_offset Offset: (0,0)
trace:d3d9nine:DRIPresent_AddRef 0x1c26e8 increasing refcount to 2.
trace:d3d9nine:DRIPresent_SetPresentParameters This=0x1c26e8, params=0x7d8ec94, focus_window=0x20082, params->hDeviceWindow=0x20082
trace:d3d9nine:DRIPresent_SetPresentParameters Nothing changed.
trace:d3d9nine:dri3_window_buffer_from_dmabuf present_priv=0x1c2018 dmaBufFd=99
trace:d3d9nine:dri3_window_buffer_from_dmabuf present_priv=0x1c2018 dmaBufFd=99
trace:d3d9nine:PRESENTDestroyPixmapContent Releasing pixmap priv 0x1c20b0
003b:fixme:imm:ImmGetOpenStatus (001D2E40): semi-stub
003b:fixme:imm:ImmReleaseContext (00020082, 001D2E40): stub
trace:d3d9nine:PRESENTDestroyPixmapContent Releasing pixmap priv 0x18e1b8
trace:d3d9nine:PRESENTDestroyPixmapContent Releasing pixmap priv 0x18e200
trace:d3d9nine:DRIPresent_Release 0x18d518 decreasing refcount to 1.
trace:d3d9nine:DRIPresentGroup_Release 0x18da18 decreasing refcount to 0.
trace:d3d9nine:DRIPresent_Release 0x18d518 decreasing refcount to 0.
remove.exe beginningtrace:d3d9nine:d3dadapter9_Release 0x18c9c0 decreasing refcount to 1.
trace:d3d9nine:d3dadapter9_Release 0x18c9c0 decreasing refcount to 0.
trace:d3d9nine:backend_destroy dri_backend=0x18db18
0030:fixme:msvcrt:__clean_type_info_names_internal (0x6e68d7c4) stub
0030:fixme:msvcrt:__clean_type_info_names_internal (0x7f03f6c) stub
0030:fixme:msvcrt:__clean_type_info_names_internal (0x6e4cc40c) stub
0030:fixme:msvcrt:__clean_type_info_names_internal (0x6e4b1554) stub
0030:fixme:msvcrt:__clean_type_info_names_internal (0x7a1ccac) stub
0030:fixme:msvcrt:__clean_type_info_names_internal (0x6e7503cc) stub
0030:fixme:msvcrt:__clean_type_info_names_internal (0x6d49c03c) stub
0030:fixme:msvcrt:__clean_type_info_names_internal (0x6e6b940c) stub
0030:fixme:msvcrt:__clean_type_info_names_internal (0x6eaa66ec) stub

**Comment by Pednick** [comment]
Also wanted to add which I forgot to say is that when ever I end an app with gallium nine enable like the one above which I included the WINEDEBUG, my display resets. Seems strange since that never happened in wine-staging-nine.  Thought it would be pertinent to mention in case it helps.

**Comment by Pednick** [comment]
Sorry my mistake, it does inhvoke if you press enter but not when you try to click on the "ok" icon.

**Comment by Pednick** [comment]
With the display reset fixed, this now works so I'm closing it.

**Comment by dhewg** [comment]
Nice, thanks for the feedback!
