### ISSUE TITLE
Gallium Nine draws square fog of war in Spellforce 2

### ISSUE THREAD

**Issue by SyndromeDayna** [iXit/wine-nine-standalone#64]
[Spellforce 2 under wine](https://webmshare.com/play/RyEQN)
[Spellforce 2 under nine](https://webmshare.com/play/1Z6aM)
[d3d9 apitrace](https://drive.google.com/drive/folders/1eYKyS9LWRautubYtS7geRgJF4lQ07ero?usp=sharing)

**Comment by SyndromeDayna** [comment]
I guess no one can reproduce.

**Comment by axeldavy** [comment]
Somehow I didn't notice this bug. I haven't tried yet so I cannot tell wether it is reproduceable, but with a trace, this bug report is complete enough to debug the issue.

**Comment by dhewg** [comment]
@axeldavy any progress?

**Comment by axeldavy** [comment]
I don't see any difference between the traces on nine or wine, so I must have fixed it
