### ISSUE TITLE
Some applications cause a temporary blackscreen.

### ISSUE THREAD

**Issue by llde** [iXit/wine-nine-standalone#65]
Hi, when using gallium nine some applications flash black screen  for few seconds during startup/shutdown depending to the app,

Europa Universalis 4 Launcher (tested  1.23 and 1.28 ) flash black twice while starting the launcher and once when starting the proper game.
Construction Set for Tes4:Oblivion flash black once during application close.

Also in some application while in menu or during loading, if a  native overlay is triggered (for example volume box from Plasma5) it stay stuck (or as a black square) until the next full redraw.
Needless to say that this doesn't happen at all with wined3d or D9VK.

**Comment by dhewg** [comment]
I _think_ this is fixed with v0.7, can you please retry with your apps/games?

**Comment by llde** [comment]
I can confirm the flash to dark issue is fixed
