### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by nPHYN1T3** [iXit/wine-nine-standalone#67]
err:d3d9nine:nine_set Couldn't load d3d9-nine.dll: L"Bad EXE format for %1.\r\n"

Trying with Wine 5.0 (stable) Xubuntu 18.04 GN v0.5

**Comment by dhewg** [comment]
Do you still run into this? I guess you're missing some required libraries

**Comment by nPHYN1T3** [comment]
Probably heh I haven't touched this since the bug report. I rarely have time to fool with stuff anymore. When I have a moment, I try things, if it doesn't work it goes in the bin and I move on.

**Comment by dhewg** [comment]
Yeah sorry for the delay, github notifications didn't work somehow, so totally missed this.
Closing this now, but if you run into this again let us know, thanks!

**Comment by nPHYN1T3** [comment]
No problem.
