### ISSUE TITLE
Wine erasing the d3d9.dll symlink

### ISSUE THREAD

**Issue by pedrofleck** [iXit/wine-nine-standalone#68]
Hi,
I'm having difficulties to make Gallium work on my laptop, I'm using Intel graphics (HD 5500) with Mesa 20.0 (Iris enabled by default = gallium support). However, whenever I try this with Lutris (Wine 5.2) or Steam+Proton 5.0 (and 4.18), `d3d9.dll` is erased every time and so Gallium doesn't work. The dll override of d3d9 is also erased from the settings every time I open `winecfg.exe` or the game as well as the registry in `HKEY_CURRENT_USER\Software\DllOverrides`. 
Running `ninewinecfg` does check all the 3 boxes and I can enable it and it creates the symlinks. However, when I run ninewinecfg again, the first box is unchecked again and all dll get erased.
What am I doing wrong?

Games tested: The Sims 4, Fallout New Vegas and Dead Space 2.
OS: Fedora 31 with Mesa updated from Fedora 32

**Comment by MischievousTomato** [comment]
It's a lutris thing. If you use wine from the commandline and do you own thing through there the same thing doesn't happen. I had the same issue.

**Comment by dhewg** [comment]
Thanks for the analysis!
