### ISSUE TITLE
No compatible GPU found

### ISSUE THREAD

**Issue by dukenukemx** [iXit/wine-nine-standalone#69]
I have a laptop with a Geforce Go 7950 GTX and I installed wine-nine-standalone and it says "No Compatible GPU Found".  It's using Nouveau on Linux Mint 19.3.  I did remove Nvidia 304 drivers but some things broke that I think I fixed.  Making sure to see if the GPU is compatible with gallium nine before I go reinstalling the OS to fix this.

**Comment by dhewg** [comment]
It's been a while, any progress on your end?

**Comment by dennismayr** [comment]
It used to work even using the nouveau driver, I'll try older releases and see which one works.

**Comment by dennismayr** [comment]
Fixed it in Ubuntu 20.04 with `nouveau` driver by installing the following extra packages:

`sudo apt install libgl1-mesa-glx:i386 libgl1-mesa-dri:i386 libegl1-mesa libegl1-mesa:i386 libd3dadapter9-mesa libd3dadapter9-mesa:i386`

Let me know if this worked for you @dukenukemx.
Cheers!

**Comment by dhewg** [comment]
Due to #93 it looks like this is resolved
