### ISSUE TITLE
Error trying to load ninewinecfg with dri2

### ISSUE THREAD

**Issue by kuipumu** [iXit/wine-nine-standalone#73]
I'm having a problem when I try to use dri 2, I tried loading it using dri 2 since my radeon GPU cannot use dri 3, but when I try to load ninewinecfg, I tried using Debian 10 default Wine 4.0 and also tried to use Wine 5.5 staging, I get this error, here I send the backtrace of it.

```

couldn't load main module (0)
Unhandled exception: page fault on execute access to 0xf0c2fb58 in 32-bit code (0xf0c2fb58).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:f0c2fb58 ESP:0032e6fc EBP:f1f2aba8 EFLAGS:00210212(  R- --  I   -A- - )
 EAX:f7d177d8 EBX:f7979000 ECX:f7d177d8 EDX:00000000
 ESI:f1f2aba0 EDI:f1f2ada8
Stack dump:
0x0032e6fc:  f71b6a42 f7d177d8 f76ec018 f724e5a9
0x0032e70c:  f7979000 f71b6a27 f7979000 f1f2aba0
0x0032e71c:  f71b707c f1f2aba0 00858224 000013c2
0x0032e72c:  f76ec273 88760827 0000000d 00858224
0x0032e73c:  0032e754 00858634 0032e7ac 00000010
0x0032e74c:  00001002 00005975 f1f2ce30 f1f2caf0
Backtrace:
=>0 0xf0c2fb58 (0xf1f2aba8)
  1 0xf1fa1048 (0xf1fa1048)
0xf0c2fb58: addb	%al,0x0(%eax)
Modules:
Module	Address			Debug info	Name (21 modules)
PE	  330000-  34e000	Deferred        aclui
PE	62800000-6289a000	Deferred        usp10
PE	64b40000-64b71000	Deferred        shcore
PE	65200000-655fe000	Deferred        ole32
PE	65980000-65997000	Deferred        version
PE	68c40000-68d2d000	Deferred        shlwapi
PE	6a900000-6aa48000	Deferred        setupapi
PE	6c0c0000-6c0f2000	Deferred        imm32
PE	6e8c0000-6ebb8000	Deferred        comctl32
PE	6fdc0000-6ff4d000	Deferred        rpcrt4
PE	7b000000-7b217000	Deferred        kernelbase
PE	7b420000-7b5f1000	Deferred        kernel32
PE	7bc40000-7bc57000	Deferred        ntdll
PE	7d3a0000-7d3a6000	Deferred        uxtheme
PE	7d8f0000-7d8f5000	Deferred        winex11
PE	7d9c0000-7dab4000	Deferred        user32
PE	7dc40000-7dc68000	Deferred        ucrtbase
PE	7ddf0000-7ddfe000	Deferred        gdi32
PE	7df70000-7df7d000	Deferred        advapi32
PE	7e020000-7e91c000	Deferred        shell32
PE	7eff0000-7eff3000	Deferred        wow64cpu
Threads:
process  tid      prio (all id:s are in hex)
00000008 (D) C:\windows\system32\ninewinecfg.exe
	["C:\windows\system32\ninewinecfg.exe" -p]
	0000002e    0
	00000009    0 <==
0000000e services.exe
	[C:\windows\system32\services.exe]
	0000002a    0
	00000026    0
	0000001f    0
	0000001c    0
	00000015    0
	00000010    0
	0000000f    0
00000011 plugplay.exe
	[C:\windows\system32\plugplay.exe]
	00000019    0
	00000018    0
	00000012    0
00000013 explorer.exe
	[C:\windows\system32\explorer.exe /desktop]
	00000027    0
	00000025    0
	00000024    0
	00000014    0
0000001a winedevice.exe
	[C:\windows\system32\winedevice.exe]
	00000021    0
	00000020    0
	0000001e    0
	0000001d    0
	0000001b    0
00000022 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	0000002b    0
	00000029    0
	00000028    0
	00000023    0
0000002f explorer.exe
	[C:\windows\system32\explorer.exe /desktop]
	00000033    0
	00000032    0
	00000031    0
	00000030    0
System information:
    Platform: i386
    Version: Windows 7
```

**Comment by axeldavy** [comment]
Which mesa version are you using ? Which graphic card model is it ?

**Comment by kuipumu** [comment]
I'm using Debian stable repo, Mesa version is 8.4.0-1+b1, the graphics card is:

`01:05.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RS482M [Mobility Radeon Xpress 200]`

This is a very old card, it works with DRI 2, but not DRI 3.

**Comment by axeldavy** [comment]
Whao, this graphic card is 15 years old !

Well unfortunately Gallium nine supports starts 2 generations after (R500, 2 years later).

I don't know why it crashes, as there should be graceful error message saying your card is not supported, but not sure this is worth investigating since the card is not supported anyway.

Considering the small amount of memory and the incomplete dx9 support of the card, even if it was working, you could run very very few games. I understand the appeal to run old hw, but in this case if you want to play, any cheapest pc will have heavenly performance compared to this.

**Comment by kuipumu** [comment]
Yes, I supposed it was related due to the age of the graphics card, It's integrated on and old Dell Inspiron 1501, it even has problem on the open source radeon driver that where never solved even when the fxglr was this available. Performance was even awful on Windows.

**Comment by dhewg** [comment]
I'd be interested in a backtrace to see if there's anything we can handle more gracefully.
You need a debug version to get a sane backtrace. I'm closing this now, if you manage to get one, please post the output here, thanks!
