### ISSUE TITLE
Skyrim severe graphical glitches

### ISSUE THREAD

**Issue by Charadon** [iXit/wine-nine-standalone#77]
Recently I went to play skyrim, and it has really BAD graphical glitches with gallium nine. It doesn't happen with d9vk/dxvk, and logs aren't really showing anything out of the ordinary. The log:

![image](https://user-images.githubusercontent.com/24775301/81591372-db877600-93ab-11ea-9096-e037c7166ce5.png)
(Apologies I couldn't copy and paste from the terminal for some unexplained reason)

I don't remember this happening before on earlier versions of mesa and iwne, and I'm wondering if this is a regression
Here's what the glitches look like: 
![20200511134157_1](https://user-images.githubusercontent.com/24775301/81593583-340c4280-93af-11ea-88a3-e4a1a5a8deca.jpg)
![20200511134154_1](https://user-images.githubusercontent.com/24775301/81593593-353d6f80-93af-11ea-8ed5-cadf3d298e54.jpg)

OS: Manjaro
Mesa Version: 20.0.6
Graphics Card: AMD RX 480
Wine Version: Wine Staging 5.7

Also, sorry if this isn't the right place to post this, if it isn't, point me in the right direction

**Comment by axeldavy** [comment]
Whao this is definitely bad.

Skyrim has been working on nine for a very very long time, and I played much on it.
I have a trace that I use to check regressions, and it seems fine with mesa master. I'll check 20.0.6.

**Comment by axeldavy** [comment]
Indeed mesa 20.0.6 is completly broken with nine

**Comment by Charadon** [comment]
Well, i'm atleast glad to know it isn't just me. You said it's fine with mesa master, so i'd assume I can fix this by just installing mesa-git for now?

**Comment by axeldavy** [comment]
yes it should fix it

**Comment by axeldavy** [comment]
You can also revert to 20.0.5 or wait 20.0.7 which has a fix for it and will be released in a few days.

**Comment by Charadon** [comment]
Just wanted to give an update. Updating to mesa-git (lib32-mesa-git to be more precise) does indeed solve the issue on my end
