### ISSUE TITLE
Make a release for gcc 10+

### ISSUE THREAD

**Issue by romulasry** [iXit/wine-nine-standalone#79]
This would be helping to quite a few.

**Comment by axeldavy** [comment]
What is the problem ? I just tried 10.1.0  and it works fine

**Comment by orbea** [comment]
@axeldavy I think its in reference to issue https://github.com/iXit/wine-nine-standalone/issues/75.

**Comment by dhewg** [comment]
Just released v0.6: https://github.com/iXit/wine-nine-standalone/releases/tag/v0.6
