### ISSUE TITLE
Urgent. No compatible GPU found. Intel Integrated 965.

### ISSUE THREAD

**Issue by venezuelan-folk** [iXit/wine-nine-standalone#88]
GUI debugger says:

> 1-) Loading of d3dadapter9 succeded
> 2-) d3d9-nine.dll is loadable
> 3-) creating a Direct3D 9 device succeded (But below it says no compatible GPU found)

Terminal debugger says:

> wine64 ninewinecfg
002c:fixme:winediag:LdrInitializeThunk wine-staging 5.19 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
0054:err:ole:start_rpcss Failed to start RpcSs service
**### _err:d3d9nine:present_has_d3dadapter No available backends._**
Native Direct3D 9 will be unavailable.
For more information visit https://github.com/iXit/wine-nine-standalone
err:d3d9nine:d3dadapter9_new Your display driver doesn't support native D3D9 adapters.

Running Linux Mint with LXDE. Latest MESA from oibaf.
tried DRI=3,2,1 and D3D_BACKEND=dri3,1 with no results. Please it is urgent, low resources laptop with 1,6 CPU 1GB RAM and it doesn't tell me the Graphics chipset nor vendor, but according to the factory info it has a P965G35

**Comment by axeldavy** [comment]
You probably have a GMA X3500 (G35 chipset). It is too old. Gallium nine doesn't contain legacy code for these cards.
Standard wine should work though.

**Comment by venezuelan-folk** [comment]
Thank you for such a quick answer <3

Though, what is the difference between gallium nine and standard windows? With that laptop games were playable there and wine is not working, the video image is fine but it makes such an overhead that it goes like 5FPS, and sometimes tells me that no Hardware Acceleration is compatible with that gpu, which didn't happen playing on windows.

Is it going all for the CPU instead of the GPU? Is it a bad DRI? Can I install Iris driver on that? Why not? 

I have not much time with Linux, it is confusing

**Comment by axeldavy** [comment]
As your card is very old, it is very unlikely to be supported by Iris, which supports only recent enough Intel graphic cards.
Iris is the only gallium driver for Intel cards, and gallium nine requires a gallium driver.

I don't know the state of the opengl driver for your card, to be honest. Maybe wine is slow for your card because the opengl support is not very good.

**Comment by venezuelan-folk** [comment]
Well thanks anyway for your help folk

**Comment by venezuelan-folk** [comment]
@axeldavy Man I was doing some more testings on this laptop and I have just found that with **MESA_LOADER_DRIVER_OVERRIDE=iris** I opened GIMP as lean as wanna be, intel-gpu-top showed me some improvement on the gpu usage in comparisson from before without iris. Now, glxinfo with that environment variable tells not that I have an old GPU but an Old Kernel, tells me to update into 4.6 but I have 5.4, and even tried with liquorix 5.8 and same.

I think I have made some advance, but now I want to know how to set Iris as a default driver from the booting.

https://linuxreviews.org/Intel_Iris

That page shows me the **.drirc** home config file, but even though I created it, nothing changed, I still have to set the environment manually pre launch.

This is an important thing, as it shows that **Iris** works on relatively Old and Dying computers.

Help please, I want to set it as the default driver

Cheers

**Comment by venezuelan-folk** [comment]
@axeldavy @dhewg @siro20 @chewi @PatrickRudolph @orbea @Lahvuun @sonicpp @FireBurn @kyrios123 

I have the real information of this laptop now.

It is an Intel Atom 455 with and Integrated Graphics (Close to what you said) GMA X3150.
Iris driver, YES it works on this; and considering it looks way too well to be incompatible, I want some Deep help on it, this is the easiest yet best Gallium Nine repository that I could find.

Here is the Terminal debugger of Super Smash Flash 2 with Iris Driver, IT WORKED, but like 10FPS at minimum quality, even though the game has Hardware Acceleration option inside, but I don't feel like it did nothing.

[galliumnine debugger-iris.txt](https://github.com/iXit/wine-nine-standalone/files/5420323/galliumnine.debugger-iris.txt)

And here is the debugger when I deliberately issued a wrong driver environment just to prove that this GPU is Iris capable, in this case it didn't work whatsoever.

[galliumnine debugger wrong driver.txt](https://github.com/iXit/wine-nine-standalone/files/5420324/galliumnine.debugger.wrong.driver.txt)

I'm sorry if I'm issuing some topic outside of your jurisdiction, I just want to know how the Wine, Gallium, DRI and API calls relate altogether, because I want to create my own Low Resource Low Spec Linux Distribution. I don't want to push people into buying new graphic cards or new laptops, any help is very appreciated.

Cheers

**Comment by axeldavy** [comment]
You can ask on freenode's #intel-gfx or #dri-devel. There will be Linux Intel devs who will be able to give you details about GMA X3150 support.

**Comment by dhewg** [comment]
It helps if one reads the error messages:

```
err:d3d9nine:dri2_create failed to open libEGL.so.1: libEGL.so.1: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio
err:d3d9nine:present_has_d3dadapter No available backends.
Native Direct3D 9 will be unavailable.
```

I don't know what moonspraak that is, but it sure looks like the 32bit libEGL.so wasn't found...

**Comment by dhewg** [comment]
Are you sure you need `DRM_PRIME=1`? That shouldn't be required if that Intel gpu is the only one in your system

**Comment by venezuelan-folk** [comment]
> You can ask on freenode's #intel-gfx or #dri-devel. There will be Linux Intel devs who will be able to give you details about GMA X3150 support.

I will try to go over there, thanks for the reference

**Comment by venezuelan-folk** [comment]
> It helps if one reads the error messages:
> 
> ```
> err:d3d9nine:dri2_create failed to open libEGL.so.1: libEGL.so.1: no se puede abrir el archivo del objeto compartido: No existe el archivo o el directorio
> err:d3d9nine:present_has_d3dadapter No available backends.
> Native Direct3D 9 will be unavailable.
> ```
> 
> I don't know what moonspraak that is, but it sure looks like the 32bit libEGL.so wasn't found...

I have just looked out for it, that library is installed from the oibaf repo, and I enabled DRI just in case for any bug

I don't know what else to do, literally I have done everything that I have found. I want to se the GPU overhead at 100% just to make sure that the problem is not an idle GPU. I have very high suspicion on that

**Comment by venezuelan-folk** [comment]
@dhewg @axeldavy you guys are awesome, I never thought that I would get answers so fast

**Comment by Venemo** [comment]
Hello @venezuelan-folk 

Sorry for the late answer, but maybe this helps. According to [Intel's website](https://ark.intel.com/content/www/us/en/ark/products/49491/intel-atom-processor-n455-512k-cache-1-66-ghz.html) the Atom N455 was launched in 2010 so it's a 10 years old CPU. The Iris driver supports the [Broadwell](https://en.wikipedia.org/wiki/Broadwell_(microarchitecture)) architecture and newer (also referred to as Gen8), which was released in late 2014. So, I'm sorry to report that Iris doesn't support your GPU.

Sadly, you can't use Gallium Nine there, so you need to disable Gallium Nine. Also please keep in mind that this GPU was considered quite low-end, even 10 years ago so you shouldn't expect too much from it.

**Comment by venezuelan-folk** [comment]
> Hello @venezuelan-folk
> 
> Sorry for the late answer, but maybe this helps. According to [Intel's website](https://ark.intel.com/content/www/us/en/ark/products/49491/intel-atom-processor-n455-512k-cache-1-66-ghz.html) the Atom N455 was launched in 2010 so it's a 10 years old CPU. The Iris driver supports the [Broadwell](https://en.wikipedia.org/wiki/Broadwell_(microarchitecture)) architecture and newer (also referred to as Gen8), which was released in late 2014. So, I'm sorry to report that Iris doesn't support your GPU.
> 
> Sadly, you can't use Gallium Nine there, so you need to disable Gallium Nine. Also please keep in mind that this GPU was considered quite low-end, even 10 years ago so you shouldn't expect too much from it.

No way 🥺
I find it difficult to believe that windows can handle better that hardware than linux, why is that? Propietary stuff or what is it?

**Comment by Venemo** [comment]
> I find it difficult to believe that windows can handle better that hardware than linux, why is that? Propietary stuff or what is it?

Please keep in mind that this chip is very old, and it was designed to run a desktop, not games. So I think gaming performance was never a priority for the driver developers. I don't work for Intel so I can't say for sure.

I had similar hardware about 10 years ago. It was pretty bad on Windows. It had trouble running games from the early 2000s, and I remember many games just crashed on start. Also keep in mind that Intel doesn't really provide support for these old chips on Windows either anymore. Their Linux driver is much better at compatibility and more stable than their Windows driver.

**Comment by venezuelan-folk** [comment]
Well, thank you so much for your time @Venemo 

Cheers
