### ISSUE TITLE
missing symbol on libd3dadapter9??

### ISSUE THREAD

**Issue by Askmewho** [iXit/wine-nine-standalone#89]
Hi, I am testing something extremely experimental. this is on ARM Linux with BOX86 emulator. I tried to get Gallium9 working but...

Failed to get the entry point from /usr/lib/i386-linux-gnu/d3d/d3dadapter9.so.1: Symbol "D3DAdapter9GetProc" not found in 0x16(d3dadapter9.so.1)

what's that? I tried other libd3dadapter9 libs just in case mine was "faulty"

**Comment by axeldavy** [comment]
See
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/7494
and
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/7001

**Comment by dhewg** [comment]
I don't think standalone can do anything here.
While I haven't attempted to set up box86 on arm, other have successfully, so I guess it's your box86 setup that's missing something
