### ISSUE TITLE
Segfault with wine 6.3

### ISSUE THREAD

**Issue by aerusso** [iXit/wine-nine-standalone#96]
I'm getting a segfault in wine-staging 6.3---both with bddb53a and 83b508d (v0.7, released).

I had to roll back to 6.2, uninstall wine-nine, and then upgrade wine again to get wine working again (wine-nine is still nonfunctional).

Are other people running into this?

**Comment by dhewg** [comment]
Same with vanilla wine 6.3.

Reverting wine's 93eb4dbd "ntdll: Add a separate helper for creating the initial ntdll module." fixes it for me.

**Comment by dhewg** [comment]
Attatched a wine patch that fixes it for me. Also sent upsteam.
[0001-ntdll-Fix-loading-.so-dlls.patch.gz](https://github.com/iXit/wine-nine-standalone/files/6056755/0001-ntdll-Fix-loading-.so-dlls.patch.gz)

**Comment by orbea** [comment]
> Also sent upsteam.

Do you have a link to the upstream discussion?

**Comment by dhewg** [comment]
No replies so far, but here it is:
https://www.winehq.org/pipermail/wine-devel/2021-February/181759.html
https://source.winehq.org/patches/data/200713

**Comment by dhewg** [comment]
Fixed upstream: https://source.winehq.org/git/wine.git/commitdiff/1e2b060eb15fa5216e9745cf48eb986a7721df61
