### ISSUE TITLE
IGI 2 - INVALIDCALL

### ISSUE THREAD

**Issue by dungeon007** [iXit/wine-nine-standalone#99]
Via d3d8to9, winde3d or dxvk launches a game, while nine not.
Just pops up message on start:

**Comment by dungeon007** [comment]
[igi2.png](https://postimg.cc/WFWV6C3W)

**Comment by dungeon007** [comment]
Trace:

**Comment by dungeon007** [comment]
Stipid GH 🤣

**Comment by dungeon007** [comment]
It was high compressed zip but  xz 🤣 , anyway here is the trace:
https://www.dropbox.com/s/suuotg0z5dqxfg7/igi2.trace.xz?dl=0

Actually trace runs on NINE, unlike the game itself... but at least someone could see what kind of invalid call is about.

**Comment by axeldavy** [comment]
Game seems to try to set the clipping status.
It is supposed to be invalid when vertex software rendering is not used. But as here is uses mixed vertex rendering, I guess the call should pass.
The game doesn't seem to use the feature though (it doesn't read the updated clipping status), so I guess we could just like dxvk and wined3d returns D3D_OK and not care about the feature.
